// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class AccomplishData
{
    public int Id { get; set; }

    public int? TaskLogId { get; set; }

    public int? ArticleId { get; set; }

    public int? TaskFieldId { get; set; }

    public string TaskFieldValue { get; set; }

    public int? TaskId { get; set; }

    public int? EmployeeId { get; set; }

    public double? NrOfArt { get; set; }

    public virtual Articles Article { get; set; }

    public virtual Employees Employee { get; set; }

    public virtual TaskFields TaskField { get; set; }

    public virtual TaskLogs TaskLog { get; set; }
}