// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class ApplicationViewTableColumn
{
    public int ApplicationViewTableColumnId { get; set; }

    public int ApplicationViewTableId { get; set; }

    public string ColumnName { get; set; }

    public string ColumnDescription { get; set; }

    public bool IsSystem { get; set; }

    public virtual ApplicationViewTable ApplicationViewTable { get; set; }

    public virtual ICollection<ApplicationViewTableColumnMandatoryAction> ApplicationViewTableColumnMandatoryAction { get; set; } = new List<ApplicationViewTableColumnMandatoryAction>();
}