// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class ApplicationView
{
    public int ApplicationViewId { get; set; }

    public string Name { get; set; }

    public bool? IsMainView { get; set; }

    public int? ModuleId { get; set; }

    public bool IsDialog { get; set; }

    public bool IsInactive { get; set; }

    public int? DefaultSort { get; set; }

    public virtual ICollection<ApplicationViewAction> ApplicationViewAction { get; set; } = new List<ApplicationViewAction>();

    public virtual ICollection<ApplicationViewTable> ApplicationViewTable { get; set; } = new List<ApplicationViewTable>();

    public virtual Module Module { get; set; }

    public virtual ICollection<Report> Report { get; set; } = new List<Report>();

    public virtual ICollection<UtilChangeLogSession> UtilChangeLogSession { get; set; } = new List<UtilChangeLogSession>();
}