// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class ApplicationViewAction
{
    public int ApplicationViewActionId { get; set; }

    public int? ApplicationViewId { get; set; }

    public string ActionName { get; set; }

    public string FriendlyName { get; set; }

    public virtual ApplicationView ApplicationView { get; set; }

    public virtual ICollection<EmployeesRoleApplicationViewAction> EmployeesRoleApplicationViewAction { get; set; } = new List<EmployeesRoleApplicationViewAction>();
}