// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class ApplicationViewTable
{
    public int ApplicationViewTableId { get; set; }

    public int ApplicationViewId { get; set; }

    public string TableName { get; set; }

    public int? SortPriority { get; set; }

    public string FriendlyName { get; set; }

    public string ReadableIdentifier { get; set; }

    public virtual ApplicationView ApplicationView { get; set; }

    public virtual ICollection<ApplicationViewTableColumn> ApplicationViewTableColumn { get; set; } = new List<ApplicationViewTableColumn>();
}