// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class ApplicationViewTableColumnMandatoryAction
{
    public int ApplicationViewTableColumnMandatoryActionId { get; set; }

    public int? ApplicationViewTableColumnId { get; set; }

    public string ActionName { get; set; }

    public bool IsMandatory { get; set; }

    public virtual ApplicationViewTableColumn ApplicationViewTableColumn { get; set; }
}