// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class ArticlesDefaultStocks
{
    public int Id { get; set; }

    public int? ArtId { get; set; }

    public int? StockId { get; set; }

    public int? RackId { get; set; }

    public int? ShelveId { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual Articles Art { get; set; }

    public virtual Racks Rack { get; set; }

    public virtual Shelves Shelve { get; set; }

    public virtual StocksList Stock { get; set; }
}