// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class Articles
{
    public int Id { get; set; }

    public string Nr { get; set; }

    public string Description { get; set; }

    public string Description2 { get; set; }

    public string SearchText { get; set; }

    public double? StockMin { get; set; }

    public double? QuantityDef { get; set; }

    public double? SalePrice { get; set; }

    public double? CostPrice { get; set; }

    public int? UnitId { get; set; }

    public bool? Inactive { get; set; }

    public int? CreateUserId { get; set; }

    public DateOnly? CreateDate { get; set; }

    public string Memo { get; set; }

    public int? ManufacturerId { get; set; }

    public int? MaterialId { get; set; }

    public double? Length { get; set; }

    public double? Width { get; set; }

    public double? Height { get; set; }

    public double? Weight { get; set; }

    public string CustomsTariffNr { get; set; }

    public byte[] TimeStamp { get; set; }

    public int? CurrencyId { get; set; }

    public bool? NoStock { get; set; }

    public string ManufacturerArtNr { get; set; }

    public string DefaultOrMaxStockLabel { get; set; }

    public double? CurrentPrice { get; set; }

    public virtual ICollection<AccomplishData> AccomplishData { get; set; } = new List<AccomplishData>();

    public virtual ICollection<ArticlesBarCodes> ArticlesBarCodes { get; set; } = new List<ArticlesBarCodes>();

    public virtual ICollection<ArticlesDefaultStocks> ArticlesDefaultStocks { get; set; } = new List<ArticlesDefaultStocks>();

    public virtual ICollection<ArticlesDocuments> ArticlesDocuments { get; set; } = new List<ArticlesDocuments>();

    public virtual ICollection<ArticlesGroups> ArticlesGroups { get; set; } = new List<ArticlesGroups>();

    public virtual ICollection<ArticlesImages> ArticlesImages { get; set; } = new List<ArticlesImages>();

    public virtual ICollection<ArticlesReferences> ArticlesReferencesArt { get; set; } = new List<ArticlesReferences>();

    public virtual ICollection<ArticlesReferences> ArticlesReferencesRefArt { get; set; } = new List<ArticlesReferences>();

    public virtual ICollection<ArticlesStocksMinimumDefaultQuantity> ArticlesStocksMinimumDefaultQuantity { get; set; } = new List<ArticlesStocksMinimumDefaultQuantity>();

    public virtual ICollection<ArticlesWebSites> ArticlesWebSites { get; set; } = new List<ArticlesWebSites>();

    public virtual ICollection<CheckingStocksPositions> CheckingStocksPositions { get; set; } = new List<CheckingStocksPositions>();

    public virtual ICollection<Components> Components { get; set; } = new List<Components>();

    public virtual ICollection<ConsumingArticles> ConsumingArticles { get; set; } = new List<ConsumingArticles>();

    public virtual Employees CreateUser { get; set; }

    public virtual Currencies Currency { get; set; }

    public virtual Manufacturers Manufacturer { get; set; }

    public virtual Materials Material { get; set; }

    public virtual ICollection<MovingArticlesPositions> MovingArticlesPositions { get; set; } = new List<MovingArticlesPositions>();

    public virtual ICollection<OrdersArticles> OrdersArticles { get; set; } = new List<OrdersArticles>();

    public virtual ICollection<ReceivingArticlesPositions> ReceivingArticlesPositions { get; set; } = new List<ReceivingArticlesPositions>();

    public virtual ICollection<StocksEvidence> StocksEvidence { get; set; } = new List<StocksEvidence>();

    public virtual ICollection<StocksHistory> StocksHistory { get; set; } = new List<StocksHistory>();

    public virtual ICollection<TaskDefaultArticles> TaskDefaultArticles { get; set; } = new List<TaskDefaultArticles>();

    public virtual ICollection<TaskLogUsedArticles> TaskLogUsedArticles { get; set; } = new List<TaskLogUsedArticles>();

    public virtual ICollection<UnscheduledTaskNeededArticles> UnscheduledTaskNeededArticles { get; set; } = new List<UnscheduledTaskNeededArticles>();
}