// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class ArticlesSuppliers
{
    public int Id { get; set; }

    public int ArtId { get; set; }

    public int SupplId { get; set; }

    public string SupplArtNr { get; set; }

    public byte[] TimeStamp { get; set; }
}