// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class ArticlesStocksMinimumDefaultQuantity
{
    public int Id { get; set; }

    public int? ArtId { get; set; }

    public int? StockId { get; set; }

    public double? MinimumQuantity { get; set; }

    public double? DefaultQuantity { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual Articles Art { get; set; }

    public virtual StocksList Stock { get; set; }
}