// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class ArticlesReferences
{
    public int Id { get; set; }

    public int? ArtId { get; set; }

    public int? RefArtId { get; set; }

    public int? RefTypeId { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual Articles Art { get; set; }

    public virtual Articles RefArt { get; set; }

    public virtual ReferencesTypes RefType { get; set; }
}