// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class ArticlesData
{
    public int Id { get; set; }

    public int? ArtGroupId { get; set; }

    public int? GroupFieldId { get; set; }

    public string FieldData { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual ArticlesGroups ArtGroup { get; set; }

    public virtual GroupsOfArticlesFields GroupField { get; set; }
}