// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class ArticlesWebSites
{
    public int Id { get; set; }

    public int? ArtId { get; set; }

    public string Name { get; set; }

    public string Url { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual Articles Art { get; set; }
}