// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class ArticlesGroups
{
    public int Id { get; set; }

    public int? ArtId { get; set; }

    public int? GroupId { get; set; }

    public int? NrOfArt { get; set; }

    public byte[] TimeStamp { get; set; }

    public int? Position { get; set; }

    public virtual Articles Art { get; set; }

    public virtual ICollection<ArticlesData> ArticlesData { get; set; } = new List<ArticlesData>();

    public virtual GroupsOfArticles Group { get; set; }
}