// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class BakkVoninIds
{
    public int Id { get; set; }

    public int? BakkVoninTableId { get; set; }

    public int? BakkId { get; set; }

    public int? VoninId { get; set; }

    public string Ship { get; set; }

    public byte[] TimeStamp { get; set; }
}