// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class BarcodereaderSessions
{
    public int BarcodeReaderSessionId { get; set; }

    public DateTime? LoginTime { get; set; }

    public DateTime? LogoutTime { get; set; }

    public int? EmployeeId { get; set; }

    public string IpAddress { get; set; }

    public int? PurchaseId { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual Purchases Purchase { get; set; }
}