// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class CheckingStocksSelectedShelves
{
    public int Id { get; set; }

    public int? CheckingStocksSelectedRacksId { get; set; }

    public int? ShelveId { get; set; }

    public bool? Selected { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual CheckingStocksSelectedRacks CheckingStocksSelectedRacks { get; set; }

    public virtual Shelves Shelve { get; set; }
}