// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class CheckingStocksSelectedRacks
{
    public int Id { get; set; }

    public int? CheckingStocksHeaderId { get; set; }

    public int? RackId { get; set; }

    public bool? Selected { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual CheckingStocksHeader CheckingStocksHeader { get; set; }

    public virtual ICollection<CheckingStocksSelectedShelves> CheckingStocksSelectedShelves { get; set; } = new List<CheckingStocksSelectedShelves>();

    public virtual Racks Rack { get; set; }
}