// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class CheckingStocksHeader
{
    public int Id { get; set; }

    public DateTime? Date { get; set; }

    public int? CheckedById { get; set; }

    public int? StockId { get; set; }

    public bool? Closed { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual Employees CheckedBy { get; set; }

    public virtual ICollection<CheckingStocksPositions> CheckingStocksPositions { get; set; } = new List<CheckingStocksPositions>();

    public virtual ICollection<CheckingStocksSelectedRacks> CheckingStocksSelectedRacks { get; set; } = new List<CheckingStocksSelectedRacks>();

    public virtual StocksList Stock { get; set; }
}