// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class CheckingStocksPositions
{
    public int Id { get; set; }

    public int? CheckingStocksHeaderId { get; set; }

    public int? ArtId { get; set; }

    public int? ShelveId { get; set; }

    public double? OnStockQuantity { get; set; }

    public double? CountedQuantity { get; set; }

    public byte[] TimeStamp { get; set; }

    public int? OldShelveId { get; set; }

    public virtual Articles Art { get; set; }

    public virtual CheckingStocksHeader CheckingStocksHeader { get; set; }

    public virtual Shelves OldShelve { get; set; }

    public virtual Shelves Shelve { get; set; }
}