// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class ComponentFieldComboBoxValues
{
    public int Id { get; set; }

    public int? ComponentFieldId { get; set; }

    public string ComboValue { get; set; }

    public byte[] TimeStamp { get; set; }

    public int? VoninId { get; set; }

    public virtual ComponentClassFields ComponentField { get; set; }
}