// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class Company
{
    public string Name { get; set; }

    public bool PrintPreview { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public string Fax { get; set; }

    public string City { get; set; }

    public string Country { get; set; }

    public string Telex { get; set; }

    public string Vat { get; set; }

    public string Reg { get; set; }

    public string Email { get; set; }

    public string HomePage { get; set; }

    public string Bank1 { get; set; }

    public string Bank2 { get; set; }

    public string Bank3 { get; set; }

    public string MailServer { get; set; }

    public string ReportLocation { get; set; }

    public int? DefaultDeliveryAddressId { get; set; }

    public string ReportServerUrl { get; set; }

    public string ReportPath { get; set; }

    public string CredentialUser { get; set; }

    public string CredentialPassword { get; set; }

    public string SuppliersInvoiceConfirmWebPage { get; set; }

    public int Id { get; set; }

    public DateTime? LastDatePtaskLogsListAutomatic { get; set; }

    public DateTime? LastTaskLogsExecuted { get; set; }

    public DateTime? LastExportConsumingArticlesToXmldate { get; set; }

    public DateTime? LastBackupDate { get; set; }

    public string FolderBackup { get; set; }

    public bool? Fifo { get; set; }

    public bool? OrdersShowPrice { get; set; }

    public bool? OrdersForUnscheduledTasks { get; set; }

    public int? NrDaysToDoList { get; set; }

    public bool? CountersEditable { get; set; }

    public bool? ActualizeStockMonthly { get; set; }

    public bool? PtaskLogsListAutomaticFromOpus { get; set; }

    public bool? ArtNrNumeric { get; set; }

    public bool? TaskIntervalsHistory { get; set; }

    public bool? Sfi2 { get; set; }

    public bool? DailyBackup { get; set; }

    public bool? ReferenceToComponents { get; set; }

    public bool? FaroeseLanguage { get; set; }

    public bool? ArtNrZeroBefore { get; set; }

    public bool? OperationsHistory { get; set; }

    public bool? Sfi { get; set; }

    public bool? ArtNrSpaceBefore { get; set; }

    public bool? UnscheduledTasksOnHold { get; set; }

    public bool? ComponentsQuestionNoCounter { get; set; }

    public bool? TasksAutomatic { get; set; }

    public bool? ComponentsQuestionMoveComponent { get; set; }

    public bool? AccomplishTasksRemarkMandatory { get; set; }

    public bool? UnscheduledTasksActionMandatory { get; set; }

    public bool? AccomplishTasksWithoutBelongingToTaskList { get; set; }

    public bool? NotificationsComponentMandatory { get; set; }

    public bool? ComponentsFontStrikeOutForInactive { get; set; }

    public bool? ToDoListSendEmailToEmployeesNdaysBeforeDueDate { get; set; }

    public bool? UnscheduledTasksSendEmail { get; set; }

    public string UnscheduledTasksSendEmailTo { get; set; }

    public int? SyncroBakkFolderId { get; set; }

    public int? SyncroVoninFolderId { get; set; }

    public string SyncroBakkFolderComponentTree { get; set; }

    public string SyncroVoninFolderComponentTree { get; set; }

    public bool? TaskLogsFieldsUpdated { get; set; }

    public bool? ComponentTreeFromRoot { get; set; }

    public bool? InvisibleReferencesForInactiveComponents { get; set; }

    public byte[] DocumentImg { get; set; }

    public bool? TasksHistoryUnscheduledTasksShowActionInsteadOfLastRemark { get; set; }

    public byte[] TimeStamp { get; set; }

    public int? UnscheduledTasksSendEmailOptionId { get; set; }

    public bool? ComponentTreeContainsSfionly { get; set; }

    public bool? UnscheduledTasksDeadlineOptional { get; set; }

    public bool? ComponentsAvailableRolesTabInvisible { get; set; }

    public bool? EmployeesRolesOrderedAlphabetically { get; set; }

    public string RefTo { get; set; }

    public bool? OrderStatus { get; set; }

    public bool? OrderDeadline { get; set; }

    public bool? OrderDiscount { get; set; }

    public bool? UsedArticlesAtAccomplish { get; set; }

    public string MailCredentialUser { get; set; }

    public string MailCredentialPassword { get; set; }

    public string MailForSendingFromOpus { get; set; }

    public bool? ComponentsOrderedByName { get; set; }

    public string ShortName { get; set; }

    public bool? HideOrderedByPhone { get; set; }

    public bool? TaskFieldsOrderedByNr { get; set; }

    public bool? ComponentsAllowChangingRoleForAtaskWhichIsInToDoList { get; set; }

    public string OrderTemplateSubject { get; set; }

    public string OrderTemplateMessage { get; set; }

    public bool? PrintMaintananceHistoryReportIsExtrareport { get; set; }

    public int? ToDoListTimerInterval { get; set; }

    public string CountersFile { get; set; }

    public bool? TasksWithoutIntervals { get; set; }

    public bool? PurchasesSetComponentAsThatFromGroupsOfArticlesAtInsertingConsumingArticles { get; set; }

    public bool? ComponentsOrderedBySfi { get; set; }

    public double? MthGst { get; set; }

    public bool? SendOrdersAlsoToTheContactPersonsEmails { get; set; }

    public bool? ToDoListComponentsWithoutTree { get; set; }

    public bool? DontDisplayAlreadyConsumedArticles { get; set; }

    public int? TaskIntervalsMaxNrDays { get; set; }

    public bool? ComponentsInOrdersArticles { get; set; }

    public virtual CompanyDeliveryAddress DefaultDeliveryAddress { get; set; }

    public virtual UnscheduledTasksSendEmailOptions UnscheduledTasksSendEmailOption { get; set; }
}