// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class ComponentMoveCopyLogs
{
    public int Id { get; set; }

    public int? ComponentId { get; set; }

    public DateTime? Date { get; set; }

    public int? EmployeeId { get; set; }

    public int? FromFolderId { get; set; }

    public int? ToFolderId { get; set; }

    public string MoveCopy { get; set; }

    public byte[] TimeStamp { get; set; }

    public bool? Hidden { get; set; }

    public DateTime? RealDate { get; set; }

    public virtual Components Component { get; set; }

    public virtual ICollection<ComponentMoveCopyLogsParents> ComponentMoveCopyLogsParents { get; set; } = new List<ComponentMoveCopyLogsParents>();

    public virtual Employees Employee { get; set; }

    public virtual Components FromFolder { get; set; }

    public virtual Components ToFolder { get; set; }
}