// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class ComponentGroupsOfArticles
{
    public int Id { get; set; }

    public int? ComponentId { get; set; }

    public int? GroupArtId { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual Components Component { get; set; }

    public virtual GroupsOfArticles GroupArt { get; set; }
}