// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class ComponentDocuments
{
    public int Id { get; set; }

    public int ComponentId { get; set; }

    public int? DocumentId { get; set; }

    public bool? OnTop { get; set; }

    public byte[] TimeStamp { get; set; }

    public int? VoninId { get; set; }

    public virtual Components Component { get; set; }

    public virtual Documents Document { get; set; }
}