// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class Components
{
    public int Id { get; set; }

    public string Name1 { get; set; }

    public string Name2 { get; set; }

    public int? CounterId { get; set; }

    public string SerialNr { get; set; }

    public string TypeNr { get; set; }

    public int? ParentId { get; set; }

    public int? ClassId { get; set; }

    public string TagNr { get; set; }

    public int? Position { get; set; }

    public int? GroupArtId { get; set; }

    public bool? IsComponent { get; set; }

    public bool? Inactive { get; set; }

    public string Description { get; set; }

    public int? ArtId { get; set; }

    public bool? Critical { get; set; }

    public string Sfi2 { get; set; }

    public int? ManufacturerId { get; set; }

    public int? RefComponentId { get; set; }

    public byte[] TimeStamp { get; set; }

    public string Location1 { get; set; }

    public int? VoninId { get; set; }

    public double? MonthlyRentPrice { get; set; }

    public byte[] Image { get; set; }

    public int? VoninParentId { get; set; }

    public DateTime? Date { get; set; }

    public int? SupplierId { get; set; }

    public string Specification { get; set; }

    public byte[] ImageThumbnail { get; set; }

    public virtual Articles Art { get; set; }

    public virtual ComponentClasses Class { get; set; }

    public virtual ICollection<ComponentAccess> ComponentAccess { get; set; } = new List<ComponentAccess>();

    public virtual ICollection<ComponentClassData> ComponentClassData { get; set; } = new List<ComponentClassData>();

    public virtual ICollection<ComponentDocuments> ComponentDocuments { get; set; } = new List<ComponentDocuments>();

    public virtual ICollection<ComponentGroupsOfArticles> ComponentGroupsOfArticles { get; set; } = new List<ComponentGroupsOfArticles>();

    public virtual ICollection<ComponentHours> ComponentHours { get; set; } = new List<ComponentHours>();

    public virtual ICollection<ComponentLogs> ComponentLogs { get; set; } = new List<ComponentLogs>();

    public virtual ICollection<ComponentMoveCopyLogs> ComponentMoveCopyLogsComponent { get; set; } = new List<ComponentMoveCopyLogs>();

    public virtual ICollection<ComponentMoveCopyLogs> ComponentMoveCopyLogsFromFolder { get; set; } = new List<ComponentMoveCopyLogs>();

    public virtual ICollection<ComponentMoveCopyLogs> ComponentMoveCopyLogsToFolder { get; set; } = new List<ComponentMoveCopyLogs>();

    public virtual ICollection<ComponentRoles> ComponentRoles { get; set; } = new List<ComponentRoles>();

    public virtual ICollection<ComponentSfilogs> ComponentSfilogs { get; set; } = new List<ComponentSfilogs>();

    public virtual ICollection<ComponentSuppliers> ComponentSuppliers { get; set; } = new List<ComponentSuppliers>();

    public virtual Counters Counter { get; set; }

    public virtual ICollection<Employees> Employees { get; set; } = new List<Employees>();

    public virtual ICollection<FilesTable> FilesTable { get; set; } = new List<FilesTable>();

    public virtual GroupsOfArticles GroupArt { get; set; }

    public virtual ICollection<GroupsOfArticles> GroupsOfArticles { get; set; } = new List<GroupsOfArticles>();

    public virtual Manufacturers Manufacturer { get; set; }

    public virtual ICollection<Notifications> Notifications { get; set; } = new List<Notifications>();

    public virtual ICollection<Orders> Orders { get; set; } = new List<Orders>();

    public virtual ICollection<Purchases> Purchases { get; set; } = new List<Purchases>();

    public virtual Suppliers Supplier { get; set; }

    public virtual ICollection<Tasks> Tasks { get; set; } = new List<Tasks>();

    public virtual ICollection<UnscheduledTasks> UnscheduledTasks { get; set; } = new List<UnscheduledTasks>();
}