// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class ComponentMoveCopyLogsParents
{
    public int Id { get; set; }

    public int? ComponentMoveCopyLogsId { get; set; }

    public int? TreeLevel { get; set; }

    public int? ParentComponentId { get; set; }

    public int? ParentRealComponentId { get; set; }

    public string TreeType { get; set; }

    public string Component { get; set; }

    public virtual ComponentMoveCopyLogs ComponentMoveCopyLogs { get; set; }
}