// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class ComponentClassFields
{
    public int Id { get; set; }

    public int? ComponentClassId { get; set; }

    public string FieldPrompt { get; set; }

    public int? ComponentFieldTypeId { get; set; }

    public string FieldUnit { get; set; }

    public int? FieldNr { get; set; }

    public int? ColumnNr { get; set; }

    public string FieldToolTipText { get; set; }

    public byte[] TimeStamp { get; set; }

    public int? VoninId { get; set; }

    public virtual ComponentClasses ComponentClass { get; set; }

    public virtual ICollection<ComponentClassData> ComponentClassData { get; set; } = new List<ComponentClassData>();

    public virtual ICollection<ComponentFieldComboBoxValues> ComponentFieldComboBoxValues { get; set; } = new List<ComponentFieldComboBoxValues>();

    public virtual ComponentFieldTypes ComponentFieldType { get; set; }
}