// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class ComponentHours
{
    public int Id { get; set; }

    public int ComponentId { get; set; }

    public DateTime Date { get; set; }

    public double? CurrentHours { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual Components Component { get; set; }
}