// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class ComponentFieldTypes
{
    public int Id { get; set; }

    public string FieldType { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual ICollection<ComponentClassFields> ComponentClassFields { get; set; } = new List<ComponentClassFields>();

    public virtual ICollection<DefaultComponentFields> DefaultComponentFields { get; set; } = new List<DefaultComponentFields>();
}