// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class CompanyDeliveryAddress
{
    public int Id { get; set; }

    public string ShortName { get; set; }

    public string DeliveryAddress { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual ICollection<Company> Company { get; set; } = new List<Company>();

    public virtual ICollection<Orders> Orders { get; set; } = new List<Orders>();
}