// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class ConsumingArticles
{
    public int Id { get; set; }

    public int? ArtId { get; set; }

    public int? ShelveId { get; set; }

    public DateTime? Date { get; set; }

    public int? UserId { get; set; }

    public double? Quantity { get; set; }

    public string DepartId { get; set; }

    public int? PurchaseId { get; set; }

    public double? ArtCostPrice { get; set; }

    public string Note { get; set; }

    public byte[] TimeStamp { get; set; }

    /// <summary>
    /// For MISC received directly to consume.
    /// </summary>
    public string ArticleDescription { get; set; }

    public virtual Articles Art { get; set; }

    public virtual Purchases Purchase { get; set; }

    public virtual Shelves Shelve { get; set; }

    public virtual Employees User { get; set; }
}