// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class ConsumingArticlesCheckingStocksArticlesIn
{
    public int Id { get; set; }

    public int? ConsArtChkStId { get; set; }

    public string Type { get; set; }

    public int? ArticlesInid { get; set; }

    public double? Quantity { get; set; }

    public double? Price { get; set; }
}