// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class Countries
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string ShortName { get; set; }

    public string Prefix { get; set; }

    public int? CurrencyId { get; set; }

    public int? UmascounterId { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual ICollection<Suppliers> Suppliers { get; set; } = new List<Suppliers>();
}