// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class Counters
{
    public int Id { get; set; }

    public string Counter { get; set; }

    public string TagName { get; set; }

    public bool? Inactive { get; set; }

    public double? HoursPerDay { get; set; }

    public double? Hours { get; set; }

    public int? UmascounterId { get; set; }

    public byte[] TimeStamp { get; set; }

    public int? VoninId { get; set; }

    public bool? AutomaticCounting { get; set; }

    public DateTime? LastUpdatedTime { get; set; }

    public string Description { get; set; }

    public string Sfi { get; set; }

    public virtual ICollection<ComponentLogs> ComponentLogs { get; set; } = new List<ComponentLogs>();

    public virtual ICollection<Components> Components { get; set; } = new List<Components>();
}