// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class CountersHistory
{
    public int Id { get; set; }

    public DateTime Date { get; set; }

    public int CounterId { get; set; }

    public string Counter { get; set; }

    public string TagName { get; set; }

    public bool? Inactive { get; set; }

    public double? HoursPerDay { get; set; }

    public double? Hours { get; set; }

    public byte[] TimeStamp { get; set; }
}