// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class Currencies
{
    public int Id { get; set; }

    public string Name { get; set; }

    public byte[] TimeStamp { get; set; }

    public double? ExchangeRate { get; set; }

    public DateTime? ExchangeRateDate { get; set; }

    public virtual ICollection<Articles> Articles { get; set; } = new List<Articles>();

    public virtual ICollection<Orders> Orders { get; set; } = new List<Orders>();

    public virtual ICollection<StocksEvidence> StocksEvidence { get; set; } = new List<StocksEvidence>();
}