// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class DefaultComponentFields
{
    public int Id { get; set; }

    public string FieldPrompt { get; set; }

    public int? ComponentFieldTypeId { get; set; }

    public string FieldUnit { get; set; }

    public int? FieldNr { get; set; }

    public int? ColumnNr { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual ComponentFieldTypes ComponentFieldType { get; set; }

    public virtual ICollection<DefaultComponentFieldsComboBoxValues> DefaultComponentFieldsComboBoxValues { get; set; } = new List<DefaultComponentFieldsComboBoxValues>();
}