// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class DefaultArticlesFields
{
    public int Id { get; set; }

    public string FieldPrompt { get; set; }

    public int? FieldTypeId { get; set; }

    public string FieldUnit { get; set; }

    public int? FieldNr { get; set; }

    public int? ColumnNr { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual ICollection<DefaultArticlesFieldsComboBoxValues> DefaultArticlesFieldsComboBoxValues { get; set; } = new List<DefaultArticlesFieldsComboBoxValues>();

    public virtual FieldsTypes FieldType { get; set; }
}