// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class DefaultArticlesFieldsComboBoxValues
{
    public int Id { get; set; }

    public int? DefaultArticlesFieldId { get; set; }

    public string ComboValue { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual DefaultArticlesFields DefaultArticlesField { get; set; }
}