// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class Deletedrows
{
    public int Id { get; set; }

    public int? TableId { get; set; }

    public int? RowId { get; set; }

    public string TableName { get; set; }

    public DateTime? AddedDate { get; set; }

    public byte[] TimeStamp { get; set; }
}