// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class Documents
{
    public int Id { get; set; }

    public byte[] Doc { get; set; }

    public string Extension { get; set; }

    public string Description { get; set; }

    public double? DocSize { get; set; }

    public int? CreateUserId { get; set; }

    public DateTime? CreateDate { get; set; }

    public byte[] Thumbnail { get; set; }

    public byte[] SmallJpg { get; set; }

    public byte[] TimeStamp { get; set; }

    public int? VoninId { get; set; }

    public int? TypeId { get; set; }

    public int? ChangedByUserId { get; set; }

    public DateTime? ChangedDate { get; set; }

    public int? ReplacedByUserId { get; set; }

    public DateTime? ReplacedDate { get; set; }

    public virtual ICollection<ArticlesDocuments> ArticlesDocuments { get; set; } = new List<ArticlesDocuments>();

    public virtual Employees ChangedByUser { get; set; }

    public virtual ICollection<ComponentDocuments> ComponentDocuments { get; set; } = new List<ComponentDocuments>();

    public virtual ICollection<FilesDocuments> FilesDocuments { get; set; } = new List<FilesDocuments>();

    public virtual ICollection<NotificationDocuments> NotificationDocuments { get; set; } = new List<NotificationDocuments>();

    public virtual ICollection<OrdersDocuments> OrdersDocuments { get; set; } = new List<OrdersDocuments>();

    public virtual Employees ReplacedByUser { get; set; }

    public virtual ICollection<SuppliersDocuments> SuppliersDocuments { get; set; } = new List<SuppliersDocuments>();

    public virtual ICollection<SuppliersInvoicesDocuments> SuppliersInvoicesDocuments { get; set; } = new List<SuppliersInvoicesDocuments>();

    public virtual ICollection<TaskDocuments> TaskDocuments { get; set; } = new List<TaskDocuments>();

    public virtual ICollection<TaskLogDocuments> TaskLogDocuments { get; set; } = new List<TaskLogDocuments>();

    public virtual DocumentTypes Type { get; set; }

    public virtual ICollection<UnscheduledTaskDocuments> UnscheduledTaskDocuments { get; set; } = new List<UnscheduledTaskDocuments>();
}