// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class DocumentTypes
{
    public int Id { get; set; }

    public string Type { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual ICollection<Documents> Documents { get; set; } = new List<Documents>();
}