// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class DocumentsBelongToResult
    {
        public int? DocumentID { get; set; }
        [StringLength(16)]
        public string Type { get; set; }
        [StringLength(100)]
        public string Nr { get; set; }
        public string Description { get; set; }
        public int? Deleted { get; set; }
    }
}
