// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class EmployeeApplicationViewSetting
{
    public int EmployeeViewSettingId { get; set; }

    public int? ApplicationViewId { get; set; }

    public string EmployeeCode { get; set; }

    public int? EmployeeId { get; set; }

    public string ComputerName { get; set; }

    public string ControlName { get; set; }

    public string ControlType { get; set; }

    public byte[] Concurrency { get; set; }

    public string SettingValueString { get; set; }
}