// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class EmployeesRoleApplicationViewAction
{
    public int StaffRoleApplicationViewActionId { get; set; }

    public int? StaffRoleApplicationViewId { get; set; }

    public int? ApplicationViewActionId { get; set; }

    public bool? CanExecuteAction { get; set; }

    public virtual ApplicationViewAction ApplicationViewAction { get; set; }

    public virtual EmployeesRoleApplicationView StaffRoleApplicationView { get; set; }
}