// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class Employees
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string ShortName { get; set; }

    public string Password { get; set; }

    public string Email { get; set; }

    public bool? OrdersWithArtNr { get; set; }

    public byte[] Signature { get; set; }

    public bool? Inactive { get; set; }

    public bool? SuperUser { get; set; }

    public bool? ToDoEmailNotification { get; set; }

    public int? NrDaysEmailNotificationBeforeDueDate { get; set; }

    public string WindowsName { get; set; }

    public int? LastComponentId { get; set; }

    public byte[] TimeStamp { get; set; }

    public int? VoninId { get; set; }

    public virtual ICollection<AccomplishData> AccomplishData { get; set; } = new List<AccomplishData>();

    public virtual ICollection<Articles> Articles { get; set; } = new List<Articles>();

    public virtual ICollection<CheckingStocksHeader> CheckingStocksHeader { get; set; } = new List<CheckingStocksHeader>();

    public virtual ICollection<ComponentAccess> ComponentAccess { get; set; } = new List<ComponentAccess>();

    public virtual ICollection<ComponentMoveCopyLogs> ComponentMoveCopyLogs { get; set; } = new List<ComponentMoveCopyLogs>();

    public virtual ICollection<ConsumingArticles> ConsumingArticles { get; set; } = new List<ConsumingArticles>();

    public virtual ICollection<Documents> DocumentsChangedByUser { get; set; } = new List<Documents>();

    public virtual ICollection<Documents> DocumentsReplacedByUser { get; set; } = new List<Documents>();

    public virtual ICollection<EmployeesLogs> EmployeesLogs { get; set; } = new List<EmployeesLogs>();

    public virtual ICollection<EmployeesMenu> EmployeesMenu { get; set; } = new List<EmployeesMenu>();

    public virtual ICollection<EmployeesReportPrinter> EmployeesReportPrinter { get; set; } = new List<EmployeesReportPrinter>();

    public virtual ICollection<EmployeesRoles> EmployeesRoles { get; set; } = new List<EmployeesRoles>();

    public virtual ICollection<FilesLogs> FilesLogs { get; set; } = new List<FilesLogs>();

    public virtual ICollection<FilesRemarks> FilesRemarks { get; set; } = new List<FilesRemarks>();

    public virtual ICollection<FilesTable> FilesTableClosedBy { get; set; } = new List<FilesTable>();

    public virtual ICollection<FilesTable> FilesTableCreatedBy { get; set; } = new List<FilesTable>();

    public virtual Components LastComponent { get; set; }

    public virtual ICollection<MovingArticlesHeader> MovingArticlesHeader { get; set; } = new List<MovingArticlesHeader>();

    public virtual ICollection<Notifications> NotificationsAssignedToUser { get; set; } = new List<Notifications>();

    public virtual ICollection<Notifications> NotificationsUser { get; set; } = new List<Notifications>();

    public virtual ICollection<Orders> Orders { get; set; } = new List<Orders>();

    public virtual ICollection<OrdersLocationsHistory> OrdersLocationsHistory { get; set; } = new List<OrdersLocationsHistory>();

    public virtual ICollection<OrdersLogs> OrdersLogs { get; set; } = new List<OrdersLogs>();

    public virtual ICollection<Purchases> PurchasesEmployee { get; set; } = new List<Purchases>();

    public virtual ICollection<Purchases> PurchasesProcessedBy { get; set; } = new List<Purchases>();

    public virtual ICollection<ReceivingArticlesHeader> ReceivingArticlesHeader { get; set; } = new List<ReceivingArticlesHeader>();

    public virtual ICollection<StocksEvidence> StocksEvidence { get; set; } = new List<StocksEvidence>();

    public virtual ICollection<SuppliersInvoicesEvents> SuppliersInvoicesEventsCreatedEmployee { get; set; } = new List<SuppliersInvoicesEvents>();

    public virtual ICollection<SuppliersInvoicesEvents> SuppliersInvoicesEventsToEmployee { get; set; } = new List<SuppliersInvoicesEvents>();

    public virtual ICollection<TaskIntervals> TaskIntervals { get; set; } = new List<TaskIntervals>();

    public virtual ICollection<TaskIntervalsStoppedRestarted> TaskIntervalsStoppedRestarted { get; set; } = new List<TaskIntervalsStoppedRestarted>();

    public virtual ICollection<TaskLogRemarks> TaskLogRemarks { get; set; } = new List<TaskLogRemarks>();

    public virtual ICollection<TaskLogs> TaskLogs { get; set; } = new List<TaskLogs>();

    public virtual ICollection<TaskLogsList> TaskLogsList { get; set; } = new List<TaskLogsList>();

    public virtual ICollection<Tasks> Tasks { get; set; } = new List<Tasks>();

    public virtual ICollection<UnscheduledTaskRemarks> UnscheduledTaskRemarks { get; set; } = new List<UnscheduledTaskRemarks>();

    public virtual ICollection<UnscheduledTasks> UnscheduledTasksAssignedToUser { get; set; } = new List<UnscheduledTasks>();

    public virtual ICollection<UnscheduledTasks> UnscheduledTasksCompletedUser { get; set; } = new List<UnscheduledTasks>();

    public virtual ICollection<UnscheduledTasks> UnscheduledTasksUser { get; set; } = new List<UnscheduledTasks>();
}