// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class EmployeesRoles
{
    public int Id { get; set; }

    public int? EmployeeId { get; set; }

    public int? RoleId { get; set; }

    public bool? DefaultRole { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual Employees Employee { get; set; }

    public virtual Roles Role { get; set; }
}