// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class EmployeesLogin
{
    public int LogId { get; set; }

    public int? StaffCode { get; set; }

    public DateTime? LogInTime { get; set; }

    public int? Spid { get; set; }

    public DateTime? LogOutTime { get; set; }

    public string AppVersion { get; set; }

    public string Note { get; set; }

    public string AppDescription { get; set; }

    public string DeviceName { get; set; }
}