// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class EmployeesReportPrinter
{
    public int Id { get; set; }

    public int? EmployeeId { get; set; }

    public string ComputerName { get; set; }

    public string NameOnServer { get; set; }

    public string PrinterName { get; set; }

    public virtual Employees Employee { get; set; }
}