// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class EmployeesMenu
{
    public int Id { get; set; }

    public int? EmployeeId { get; set; }

    public int? MenuTableId { get; set; }

    public bool? Visible { get; set; }

    public byte[] TimeStamp { get; set; }

    public int? LastSearchedField { get; set; }

    public virtual Employees Employee { get; set; }

    public virtual MenuTable MenuTable { get; set; }
}