// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class EmployeesRoleApplicationView
{
    public int StaffRoleApplicationViewId { get; set; }

    public int? StaffRoleId { get; set; }

    public int? ApplicationViewId { get; set; }

    public bool AllowRead { get; set; }

    public bool AllowSave { get; set; }

    public byte[] Concurrency { get; set; }

    public virtual ICollection<EmployeesRoleApplicationViewAction> EmployeesRoleApplicationViewAction { get; set; } = new List<EmployeesRoleApplicationViewAction>();

    public virtual Roles StaffRole { get; set; }
}