// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class EmployeesLogs
{
    public int Id { get; set; }

    public int? EmployeeId { get; set; }

    public DateTime? LogInTime { get; set; }

    public DateTime? LogOutTime { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual Employees Employee { get; set; }
}