// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class EvArticlesConsumptionShelvesRacksStocks
{
    public int ConsumptionArticleId { get; set; }

    public int? ArticleId { get; set; }

    public int? ShelveId { get; set; }

    public DateTime? Date { get; set; }

    public int? UserId { get; set; }

    public double? Quantity { get; set; }

    public string DepartId { get; set; }

    public int? PurchaseId { get; set; }

    public double? ArtCostPrice { get; set; }

    public string Note { get; set; }

    public string ArticleDescription { get; set; }

    public string ShelveName { get; set; }

    public int? RackId { get; set; }

    public string RackName { get; set; }

    public int? StockId { get; set; }

    public string StockShortName { get; set; }

    public string StockName { get; set; }

    public string Adress { get; set; }

    public string ArticleNr { get; set; }
}