// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class Expenses
{
    public int Id { get; set; }

    public int? ResourceId { get; set; }

    public int? SuppliersInvoiceId { get; set; }

    public string Description { get; set; }

    public double? Cost { get; set; }

    public int? FileId { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual FilesTable File { get; set; }

    public virtual ResourcesTable Resource { get; set; }

    public virtual SuppliersInvoices SuppliersInvoice { get; set; }
}