// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class FArticlesOpenedOrdersResult
    {
        public int? ID { get; set; }
        public int? OrderNr { get; set; }
        [StringLength(100)]
        public string Description { get; set; }
        public int? SupplID { get; set; }
        [StringLength(100)]
        public string SupplName { get; set; }
        [StringLength(100)]
        public string SupplAdress1 { get; set; }
        [StringLength(100)]
        public string SupplAdress2 { get; set; }
        [StringLength(100)]
        public string SupplAdress3 { get; set; }
        [StringLength(100)]
        public string SupplAdress4 { get; set; }
        public int? SupplCityID { get; set; }
        public int? SupplCountryID { get; set; }
        [StringLength(30)]
        public string SupplPhone { get; set; }
        [StringLength(30)]
        public string SupplFax { get; set; }
        [StringLength(100)]
        public string SupplEmail { get; set; }
        public DateTime? CreateDate { get; set; }
        public DateTime? CompleteDate { get; set; }
        public DateTime? DeliveryDate { get; set; }
        public bool? OrderedByPhone { get; set; }
        [StringLength(100)]
        public string DepartID { get; set; }
        public int? AccountID { get; set; }
        public int? OurPersonID { get; set; }
        public int? SupplPersonID { get; set; }
        public int? CreateUserID { get; set; }
        public double? Value { get; set; }
        public int? CurrencyID { get; set; }
        public bool? Printed { get; set; }
        public DateTime? Regtime { get; set; }
        public bool? Closed { get; set; }
        public int? CompanyDeliveryAddressID { get; set; }
        public bool? Deleted { get; set; }
        public bool? Sent { get; set; }
        public byte[] TimeStamp { get; set; }
        [StringLength(1000)]
        public string Remarks { get; set; }
        [StringLength(1000)]
        public string DeliveryTerms { get; set; }
        [StringLength(1000)]
        public string TransportMode { get; set; }
        public double? NrOfColli { get; set; }
        public double? TotalWeight { get; set; }
        public int? ShipperID { get; set; }
        public int? ShipperPersonID { get; set; }
        public int? ComponentID { get; set; }
        public DateOnly? Deadline { get; set; }
        [StringLength(100)]
        public string SupplPostalCode { get; set; }
        public string Remark { get; set; }
        public byte[] Image { get; set; }
        [StringLength(5)]
        public string CurrencyName { get; set; }
    }
}
