// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class FArticlesBelowMinimumStockResult
    {
        public int? artID { get; set; }
        public double? QUANTITY { get; set; }
        public double? StockMin { get; set; }
    }
}
