// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class FComponentMoveCopyLogsResult
    {
        public int? Reference { get; set; }
        public int ID { get; set; }
        public int? ComponentID { get; set; }
        [StringLength(50)]
        public string EmployeeName { get; set; }
        public bool? Hidden { get; set; }
        public DateTime? Date { get; set; }
        public DateTime? RealDate { get; set; }
        [StringLength(50)]
        public string MoveCopy { get; set; }
        public string FromFolderName { get; set; }
        public string ToFolderName { get; set; }
    }
}
