// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class FComponentTreeResult
    {
        public int? ID { get; set; }
        public int? CounterID { get; set; }
        public double? Hours { get; set; }
        public bool? Inactive { get; set; }
        [StringLength(1001)]
        public string SFI { get; set; }
        [StringLength(5000)]
        public string ComponentTree { get; set; }
    }
}
