// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class FComponentListResult
    {
        public int? ID { get; set; }
        [StringLength(100)]
        public string field1 { get; set; }
        [StringLength(100)]
        public string field2 { get; set; }
        [StringLength(100)]
        public string field3 { get; set; }
        [StringLength(100)]
        public string field4 { get; set; }
        [StringLength(100)]
        public string field5 { get; set; }
        [StringLength(100)]
        public string field6 { get; set; }
    }
}
