// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class FComponentAllParentsResult
    {
        public int? ID { get; set; }
        public int? CompID { get; set; }
        public int? RealCompId { get; set; }
    }
}
