// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class FEmployeesByRoleIDResult
    {
        public int ID { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        public string ShortName { get; set; }
        [StringLength(50)]
        public string Password { get; set; }
        [StringLength(100)]
        public string Email { get; set; }
        public bool? OrdersWithArtNr { get; set; }
        public byte[] Signature { get; set; }
        public bool? Inactive { get; set; }
        public bool? SuperUser { get; set; }
        public bool? ToDoEmailNotification { get; set; }
        public int? NrDaysEmailNotificationBeforeDueDate { get; set; }
        [StringLength(300)]
        public string WindowsName { get; set; }
        public int? LastComponentID { get; set; }
        public byte[] TimeStamp { get; set; }
    }
}
