// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class FFilesArticlesResult
    {
        public int FileID { get; set; }
        public int? ArtID { get; set; }
        [StringLength(100)]
        public string nr { get; set; }
        [StringLength(500)]
        public string description { get; set; }
        public double? quantity { get; set; }
        public double? CostPrice { get; set; }
    }
}
