// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class FGetStock_NEWResult
    {
        public int? ArtID { get; set; }
        public int? ShelveID { get; set; }
        public int? RackID { get; set; }
        public int? StockID { get; set; }
        public double? Quantity { get; set; }
    }
}
