// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class FGetArticleStockInformationResult
    {
        [StringLength(100)]
        public string ArtNr { get; set; }
        [StringLength(500)]
        public string ArtDescription { get; set; }
        [StringLength(100)]
        public string ManufacturerArtNr { get; set; }
        public double? TotalStock { get; set; }
        public double? OpenedOrdersQuantity { get; set; }
    }
}
