// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class FGetTaskLogsResult
    {
        [StringLength(100)]
        public string FIELDName1 { get; set; }
        [StringLength(100)]
        public string FIELDName2 { get; set; }
        [StringLength(100)]
        public string FIELDName3 { get; set; }
        [StringLength(100)]
        public string FIELDName4 { get; set; }
        [StringLength(100)]
        public string FIELDName5 { get; set; }
        [StringLength(100)]
        public string FIELDName6 { get; set; }
        [StringLength(100)]
        public string FIELDName7 { get; set; }
    }
}
