// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class FGetOperationsResult
    {
        public int? ID { get; set; }
        public int? ParentRowID { get; set; }
        public int? ArtID { get; set; }
        public string Operation { get; set; }
        public DateTime? Date { get; set; }
        public int? OutputShelve { get; set; }
        public int? OutputRack { get; set; }
        public int? OutputStock { get; set; }
        public int? InputShelve { get; set; }
        public int? InputRack { get; set; }
        public int? InputStock { get; set; }
        public double? Quantity { get; set; }
        [StringLength(500)]
        public string Employee { get; set; }
        public double? Price { get; set; }
        [StringLength(5000)]
        public string ComponentTree { get; set; }
        [StringLength(1000)]
        public string UnscheduledTask { get; set; }
        public bool? NewLocation { get; set; }
        public bool? DirectToConsumption { get; set; }
        public int? CurrencyID { get; set; }
        public int? ComponentID { get; set; }
        [StringLength(50)]
        public string OutputShelveName { get; set; }
        [StringLength(50)]
        public string OutputRackName { get; set; }
        [StringLength(50)]
        public string OutputStockName { get; set; }
        [StringLength(50)]
        public string InputShelveName { get; set; }
        [StringLength(50)]
        public string InputRackName { get; set; }
        [StringLength(50)]
        public string InputStockName { get; set; }
    }
}
