// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class FGetArticleTaskComponentIntervalResult
    {
        [StringLength(1000)]
        public string Task { get; set; }
        [StringLength(5000)]
        public string ComponentTree { get; set; }
        [StringLength(5000)]
        public string IntervalChar { get; set; }
        public double? NrOfArt { get; set; }
    }
}
