// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class FieldsTypes
{
    public int Id { get; set; }

    public string FieldType { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual ICollection<DefaultArticlesFields> DefaultArticlesFields { get; set; } = new List<DefaultArticlesFields>();

    public virtual ICollection<GroupsOfArticlesFields> GroupsOfArticlesFields { get; set; } = new List<GroupsOfArticlesFields>();

    public virtual ICollection<TableFields> TableFields { get; set; } = new List<TableFields>();

    public virtual ICollection<TaskFields> TaskFields { get; set; } = new List<TaskFields>();
}