// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class FilesTable
{
    public int Id { get; set; }

    public int? Nr { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int CreatedById { get; set; }

    public int? ComponentId { get; set; }

    public bool? Deleted { get; set; }

    public bool? Closed { get; set; }

    public int? ClosedById { get; set; }

    public DateTime? ClosedDate { get; set; }

    public string Status { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual Employees ClosedBy { get; set; }

    public virtual Components Component { get; set; }

    public virtual Employees CreatedBy { get; set; }

    public virtual ICollection<Expenses> Expenses { get; set; } = new List<Expenses>();

    public virtual ICollection<FilesDocuments> FilesDocuments { get; set; } = new List<FilesDocuments>();

    public virtual ICollection<FilesLogs> FilesLogs { get; set; } = new List<FilesLogs>();

    public virtual ICollection<FilesRemarks> FilesRemarks { get; set; } = new List<FilesRemarks>();

    public virtual ICollection<Notifications> Notifications { get; set; } = new List<Notifications>();

    public virtual ICollection<SuppliersInvoices> SuppliersInvoices { get; set; } = new List<SuppliersInvoices>();

    public virtual ICollection<UnscheduledTaskDependence> UnscheduledTaskDependence { get; set; } = new List<UnscheduledTaskDependence>();

    public virtual ICollection<UnscheduledTasks> UnscheduledTasks { get; set; } = new List<UnscheduledTasks>();
}