// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class FilesRemarks
{
    public int Id { get; set; }

    public int? FileId { get; set; }

    public string Remark { get; set; }

    public int? EmployeeId { get; set; }

    public DateTime? Date { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual Employees Employee { get; set; }

    public virtual FilesTable File { get; set; }
}