// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class FIntervalsDueDateResult
    {
        public int? ID { get; set; }
        public int? TaskIntervalsID { get; set; }
        public int? TaskID { get; set; }
        public int? ComponentID { get; set; }
        public int? TaskTypeID { get; set; }
        public int? RoleID { get; set; }
        public double? RunningHours { get; set; }
        public DateTime? LastLogDate { get; set; }
        public DateTime? NextLogDate { get; set; }
        public double? LeftTime { get; set; }
        [StringLength(2000)]
        public string LeftTimeChar { get; set; }
        [StringLength(5000)]
        public string IntervalChar { get; set; }
    }
}
