// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class FLastTaskLogRowResult
    {
        public int ID { get; set; }
        public int TaskID { get; set; }
        public int? TaskIntervalsID { get; set; }
        public DateTime? CompletedTime { get; set; }
        public int? UserID { get; set; }
        public int? TaskLogsListID { get; set; }
        public int? TaskTypeID { get; set; }
        public double? RunningHours { get; set; }
        [StringLength(5000)]
        public string Remark { get; set; }
        public int? ManHours { get; set; }
        public bool? FirstTaskLog { get; set; }
        public bool? Automatic { get; set; }
        public DateTime? NextDate { get; set; }
        public DateTime? UserCompletedTime { get; set; }
        [StringLength(1000)]
        public string Field1 { get; set; }
        [StringLength(1000)]
        public string Field2 { get; set; }
        [StringLength(1000)]
        public string Field3 { get; set; }
        [StringLength(1000)]
        public string Field4 { get; set; }
        public byte[] TimeStamp { get; set; }
        public DateTime? AddedDate { get; set; }
        public bool? Priority { get; set; }
        [StringLength(1000)]
        public string Field5 { get; set; }
        [StringLength(1000)]
        public string Field6 { get; set; }
        [StringLength(1000)]
        public string Field7 { get; set; }
        [StringLength(5000)]
        public string PostponeRemark { get; set; }
        public int? VoninID { get; set; }
    }
}
