// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class FRptTaskSummary_AccomplishedTasksResult
    {
        public int ID { get; set; }
        public int? TaskIntervalsID { get; set; }
        public int? UserID { get; set; }
        public int? ComponentID { get; set; }
        [StringLength(1000)]
        public string TaskName { get; set; }
        [StringLength(5000)]
        public string TaskDescription { get; set; }
        [StringLength(5000)]
        public string ComponentTree { get; set; }
        public DateTime? completedTime { get; set; }
        [StringLength(500)]
        public string TaskTypeName { get; set; }
        [StringLength(5000)]
        public string action { get; set; }
        [StringLength(50)]
        public string UserName { get; set; }
        [StringLength(20)]
        public string RoleName { get; set; }
        public int? TOPParentID { get; set; }
    }
}
