// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class FRptTaskSummary_UnscheduledTasksResult
    {
        public int ID { get; set; }
        public int? NotificationID { get; set; }
        public string Description { get; set; }
        public DateTime? Date { get; set; }
        public int? UserID { get; set; }
        [StringLength(100)]
        public string Title { get; set; }
        public int? Nr { get; set; }
        public int? CreatedRoleID { get; set; }
        public int? ResponsibleRoleID { get; set; }
        public int? ComponentID { get; set; }
        public bool Priority { get; set; }
        public bool Completed { get; set; }
        public DateTime? CompletedTime { get; set; }
        public bool? OnHold { get; set; }
        public DateTime? Deadline { get; set; }
        public int? CompletedUserID { get; set; }
        public string Action { get; set; }
        public int? FileID { get; set; }
        [Column(" IsNew")]
        [StringLength(3)]
        public string IsNew { get; set; }
        [StringLength(20)]
        public string RespRole { get; set; }
        [StringLength(50)]
        public string CreateUser { get; set; }
        [StringLength(50)]
        public string CompleteUser { get; set; }
        [StringLength(100)]
        public string FileTitle { get; set; }
        public int NrDoc { get; set; }
        public int? TOPParentID { get; set; }
        [StringLength(5000)]
        public string ComponentTree { get; set; }
    }
}
