// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class FSubComponentsAndParameterComponentResult
    {
        public int? ID { get; set; }
        public int? PARENTID { get; set; }
        public int? TOPParentID { get; set; }
        [StringLength(4000)]
        public string ComponentTree { get; set; }
        [StringLength(500)]
        public string Name1 { get; set; }
    }
}
