// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class FSuppliersResult
    {
        public int? ID { get; set; }
        [StringLength(500)]
        public string Name { get; set; }
    }
}
