// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class FSuppliersInvoicesStatusResult
    {
        public int? ID { get; set; }
        public int? InvoiceEventTypeID { get; set; }
        [StringLength(30)]
        public string Event { get; set; }
        public int? EmployeeID { get; set; }
        public DateTime? EventTime { get; set; }
    }
}
