// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class FTasksStatusResult
    {
        public int? TaskIntervalsID { get; set; }
        public int? TaskID { get; set; }
        public int? ComponentID { get; set; }
        public int? TaskTypeID { get; set; }
        public int? RoleID { get; set; }
        public double? RunningHours { get; set; }
        public DateTime? LastLogDate { get; set; }
        public DateTime? NextLogDate { get; set; }
        public double? LeftTime { get; set; }
        [StringLength(2000)]
        public string LeftTimeChar { get; set; }
        [StringLength(5000)]
        public string IntervalChar { get; set; }
        [StringLength(1000)]
        public string TaskName { get; set; }
        [StringLength(5000)]
        public string ComponentTree { get; set; }
        [StringLength(50)]
        public string TaskType { get; set; }
        [StringLength(20)]
        public string RoleName { get; set; }
        public int? IntervalTypeID { get; set; }
        public int? Interval { get; set; }
    }
}
