// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class FUsedArticlesScheduledTasksResult
    {
        public int? ArtID { get; set; }
        [StringLength(100)]
        public string Nr { get; set; }
        [StringLength(500)]
        public string Description { get; set; }
        public double? NrOfArt { get; set; }
    }
}
