// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class FWEBGetStockResult
    {
        public int? ARTID { get; set; }
        [StringLength(100)]
        public string Nr { get; set; }
        [StringLength(500)]
        public string Description { get; set; }
        public int? STOCKID { get; set; }
        [StringLength(100)]
        public string StockName { get; set; }
        public double? QUANTITY { get; set; }
        [StringLength(50)]
        public string UM { get; set; }
        [StringLength(50)]
        public string Quantity_UM { get; set; }
    }
}
