// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class GetComponentsWEBAppResult
    {
        public int? ID { get; set; }
        [StringLength(500)]
        public string Name1 { get; set; }
        public bool? IsComponent { get; set; }
        public int? RefComponentID { get; set; }
        public int? ClassID { get; set; }
        [StringLength(1)]
        public string AccessLevelEmp { get; set; }
        [StringLength(1)]
        public string AccessLevelRole { get; set; }
        [StringLength(500)]
        public string TagNr { get; set; }
        [StringLength(500)]
        public string sfi2 { get; set; }
        public int? position { get; set; }
        public byte[] Image { get; set; }
        [StringLength(50)]
        public string FieldPrompt { get; set; }
        [StringLength(5000)]
        public string FieldData { get; set; }
        [StringLength(5000)]
        public string ComponentTree { get; set; }
    }
}
