// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class GetEmployeeComponentAccessResult
    {
        public int ComponentId { get; set; }
        [StringLength(500)]
        public string ComponentName { get; set; }
        public string AccessLevel { get; set; }
    }
}
