// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class GetStockBarCodeResult
    {
        [StringLength(50)]
        public string Stock { get; set; }
        [StringLength(20)]
        public string Rack { get; set; }
        [StringLength(20)]
        public string Shelve { get; set; }
        public double? Quantity { get; set; }
        public int? ShelveID { get; set; }
    }
}
