// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class GroupsOfArticlesFields
{
    public int Id { get; set; }

    public int? GroupId { get; set; }

    public string FieldPrompt { get; set; }

    public int? FieldTypeId { get; set; }

    public string FieldUnit { get; set; }

    public int? FieldNr { get; set; }

    public int? ColumnNr { get; set; }

    public string FieldToolTipText { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual ICollection<ArticlesData> ArticlesData { get; set; } = new List<ArticlesData>();

    public virtual FieldsTypes FieldType { get; set; }

    public virtual GroupsOfArticles Group { get; set; }

    public virtual ICollection<GroupsOfArticlesFieldsComboBoxValues> GroupsOfArticlesFieldsComboBoxValues { get; set; } = new List<GroupsOfArticlesFieldsComboBoxValues>();
}