// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class GroupsOfArticles
{
    public int Id { get; set; }

    public string Name { get; set; }

    public bool? SpareList { get; set; }

    public int? ParentId { get; set; }

    public byte[] TimeStamp { get; set; }

    public int? ComponentIdforPurchases { get; set; }

    public virtual ICollection<ArticlesGroups> ArticlesGroups { get; set; } = new List<ArticlesGroups>();

    public virtual ICollection<ComponentGroupsOfArticles> ComponentGroupsOfArticles { get; set; } = new List<ComponentGroupsOfArticles>();

    public virtual Components ComponentIdforPurchasesNavigation { get; set; }

    public virtual ICollection<Components> Components { get; set; } = new List<Components>();

    public virtual ICollection<GroupsOfArticlesFields> GroupsOfArticlesFields { get; set; } = new List<GroupsOfArticlesFields>();
}