// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class HistoryChangeTables
{
    public int Id { get; set; }

    public string TableName { get; set; }

    public string StaffCode { get; set; }

    public string ActionType { get; set; }

    public DateTime? ChangeTime { get; set; }

    public int? Pkvalue { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual ICollection<HistoryChangeColumns> HistoryChangeColumns { get; set; } = new List<HistoryChangeColumns>();
}