// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class HistoryChangeColumns
{
    public int Id { get; set; }

    public string ColumnName { get; set; }

    public string OldValue { get; set; }

    public string NewValue { get; set; }

    public bool? IsKey { get; set; }

    public int? HistoryChangeTableId { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual HistoryChangeTables HistoryChangeTable { get; set; }
}