// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class InsertProductionLocationResult
    {
        public int ID { get; set; }
        public int? ComponentID { get; set; }
        [StringLength(1000)]
        public string Name { get; set; }
        [StringLength(5000)]
        public string Description { get; set; }
        public int? LastTaskLogID { get; set; }
        public bool? StopRequired { get; set; }
        public bool? Automatic { get; set; }
        public int? ManHours { get; set; }
        public int? CreateUserID { get; set; }
        public DateTime? CreateDate { get; set; }
        public bool? Inactive { get; set; }
        public int? TaskClassID { get; set; }
        public byte[] TimeStamp { get; set; }
        public int? VoninID { get; set; }
        public bool? Stopped { get; set; }
    }
}
