// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class IntervalTypes
{
    public int Id { get; set; }

    public string Type { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual ICollection<TaskIntervals> TaskIntervals { get; set; } = new List<TaskIntervals>();
}