// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class Ipolpo
{
    public int Id { get; set; }

    public string Ipolpo1 { get; set; }

    public virtual ICollection<Orders> Orders { get; set; } = new List<Orders>();
}