// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class LoadSuppliersWPFResult
    {
        public int ID { get; set; }
        [StringLength(100)]
        public string Name { get; set; }
        [StringLength(100)]
        public string Adress1 { get; set; }
        [StringLength(100)]
        public string Adress2 { get; set; }
        [StringLength(100)]
        public string Adress3 { get; set; }
        [StringLength(100)]
        public string Adress4 { get; set; }
        [StringLength(100)]
        public string PostalCode { get; set; }
        [StringLength(150)]
        public string Country { get; set; }
        [StringLength(30)]
        public string Phone { get; set; }
        [StringLength(30)]
        public string Fax { get; set; }
        public string Memo { get; set; }
        [StringLength(100)]
        public string Email { get; set; }
    }
}
