// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class LoadConsumingArticlesResult
    {
        public int ID { get; set; }
        public int? ArtID { get; set; }
        public int? ShelveID { get; set; }
        public DateTime? Date { get; set; }
        public int? UserID { get; set; }
        public double? Quantity { get; set; }
        [StringLength(100)]
        public string DepartID { get; set; }
        public int? PurchaseID { get; set; }
        public double? ArtCostPrice { get; set; }
        [StringLength(2147483647)]
        public string Note { get; set; }
        public byte[] TimeStamp { get; set; }
        [StringLength(500)]
        public string ArticleDescription { get; set; }
        public double? AlreadyConsumedQuantity { get; set; }
        public int? TaskLogID { get; set; }
        public int? UnscheduledTaskID { get; set; }
        public int? ComponentID { get; set; }
        public bool Processed { get; set; }
        [StringLength(100)]
        public string ArtNr { get; set; }
        [StringLength(500)]
        public string ArtDescription { get; set; }
        [StringLength(5)]
        public string ArtUnit { get; set; }
        public double? OnStockQuantity { get; set; }
        [StringLength(100)]
        public string Shelve { get; set; }
        [StringLength(100)]
        public string Rack { get; set; }
        [StringLength(100)]
        public string Stock { get; set; }
        public bool? AlreadyConsumed { get; set; }
        [StringLength(30)]
        public string AlreadyConsumedText { get; set; }
    }
}
