// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class LoadTaskDefaultArticlesResult
    {
        public int? ID { get; set; }
        public int? TaskID { get; set; }
        public int? ArtID { get; set; }
        public double? Quantity { get; set; }
        [StringLength(100)]
        public string ArtNr { get; set; }
        [StringLength(500)]
        public string ArtDescription { get; set; }
        [StringLength(5)]
        public string ArtUnit { get; set; }
        public int? ShelveID { get; set; }
        public double? OnStockQuantity { get; set; }
    }
}
