// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class Materials
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual ICollection<Articles> Articles { get; set; } = new List<Articles>();
}