// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class MenuTable
{
    public int Id { get; set; }

    public int MenuNr { get; set; }

    public int? ParentNr { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int? LevelNr { get; set; }

    public byte[] TimeStamp { get; set; }

    public string DescriptionCh { get; set; }

    public virtual ICollection<EmployeesMenu> EmployeesMenu { get; set; } = new List<EmployeesMenu>();
}