// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class Module
{
    public int ModuleId { get; set; }

    public string ModuleName { get; set; }

    public virtual ICollection<ApplicationView> ApplicationView { get; set; } = new List<ApplicationView>();
}