// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class MonthDays
{
    public int Id { get; set; }

    public int? TaskIntervalsId { get; set; }

    public int? Day { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual TaskIntervals TaskIntervals { get; set; }
}