// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class MovingArticlesPositions
{
    public int Id { get; set; }

    public int? MovingarticlesHeaderid { get; set; }

    public int? Artid { get; set; }

    public int? Shelveid1 { get; set; }

    public int? Shelveid2 { get; set; }

    public double? Quantity { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual Articles Art { get; set; }

    public virtual MovingArticlesHeader MovingarticlesHeader { get; set; }

    public virtual Shelves Shelveid1Navigation { get; set; }

    public virtual Shelves Shelveid2Navigation { get; set; }
}