// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class MovingArticlesHeader
{
    public int Id { get; set; }

    public int? Stockid1 { get; set; }

    public int? Stockid2 { get; set; }

    public DateTime? Date { get; set; }

    public bool? Closed { get; set; }

    public int? Movedbyid { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual Employees Movedby { get; set; }

    public virtual ICollection<MovingArticlesPositions> MovingArticlesPositions { get; set; } = new List<MovingArticlesPositions>();

    public virtual StocksList Stockid1Navigation { get; set; }

    public virtual StocksList Stockid2Navigation { get; set; }
}