// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class NotificationDocuments
{
    public int Id { get; set; }

    public int NotificationId { get; set; }

    public int DocumentId { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual Documents Document { get; set; }

    public virtual Notifications Notification { get; set; }
}