// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class Notifications
{
    public int Id { get; set; }

    public string Description { get; set; }

    public DateTime? Date { get; set; }

    public int? UserId { get; set; }

    public string Title { get; set; }

    public int? Nr { get; set; }

    public int? CreatedRoleId { get; set; }

    public int? ResponsibleRoleId { get; set; }

    public int? NotificationTypeId { get; set; }

    public int? ComponentId { get; set; }

    public bool? Priority { get; set; }

    public bool? Completed { get; set; }

    public string Remark { get; set; }

    public DateTime? CompletedTime { get; set; }

    public int? CompletedUserId { get; set; }

    public int? FileId { get; set; }

    public byte[] TimeStamp { get; set; }

    public int? ParentId { get; set; }

    public DateTime? NotificationDate { get; set; }

    public int? AssignedToUserId { get; set; }

    public virtual Employees AssignedToUser { get; set; }

    public virtual Components Component { get; set; }

    public virtual Roles CreatedRole { get; set; }

    public virtual FilesTable File { get; set; }

    public virtual ICollection<Notifications> InverseParent { get; set; } = new List<Notifications>();

    public virtual ICollection<NotificationDocuments> NotificationDocuments { get; set; } = new List<NotificationDocuments>();

    public virtual NotificationTypes NotificationType { get; set; }

    public virtual Notifications Parent { get; set; }

    public virtual ICollection<UnscheduledTasks> UnscheduledTasks { get; set; } = new List<UnscheduledTasks>();

    public virtual Employees User { get; set; }
}