// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class NotificationTypes
{
    public int Id { get; set; }

    public string ShortName { get; set; }

    public string Name { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual ICollection<Notifications> Notifications { get; set; } = new List<Notifications>();

    public virtual ICollection<TableFields> TableFields { get; set; } = new List<TableFields>();
}