// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class OperationHours
{
    public string TagName { get; set; }

    public string Description { get; set; }

    public double? Hours { get; set; }

    public DateTime? UpdateTime { get; set; }

    public DateTime? FirstUpdateTime { get; set; }

    public int? LastRows { get; set; }

    public string Location { get; set; }

    public bool? AutoIncremented { get; set; }
}