// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class OrdersArticles
{
    public int Id { get; set; }

    public int? Position { get; set; }

    public int OrderId { get; set; }

    public int? ArtId { get; set; }

    public double? Quantity { get; set; }

    public string Unit { get; set; }

    public string Description { get; set; }

    public string QuantChar { get; set; }

    public string Received { get; set; }

    public double? Price { get; set; }

    public double? Discount { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual Articles Art { get; set; }

    public virtual Orders Order { get; set; }

    public virtual ICollection<ReceivingArticlesPositions> ReceivingArticlesPositions { get; set; } = new List<ReceivingArticlesPositions>();

    public virtual ICollection<SuppliersInvoicesOrdersArticles> SuppliersInvoicesOrdersArticles { get; set; } = new List<SuppliersInvoicesOrdersArticles>();

    public virtual ICollection<UnscheduledTaskNeededArticles> UnscheduledTaskNeededArticles { get; set; } = new List<UnscheduledTaskNeededArticles>();
}