// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class OrdersLocationsHistory
{
    public int Id { get; set; }

    public int? OrderId { get; set; }

    public int? ShelveId { get; set; }

    public int? Nr { get; set; }

    public DateTime? Date { get; set; }

    public int? UserId { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual Orders Order { get; set; }

    public virtual Shelves Shelve { get; set; }

    public virtual Employees User { get; set; }
}