// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class OrdersLogs
{
    public int Id { get; set; }

    public int OrderId { get; set; }

    public DateTime Date { get; set; }

    public int EmployeeId { get; set; }

    public string Computer { get; set; }

    public string Txt { get; set; }

    public byte[] TimeStamp { get; set; }

    public Guid? SynchId { get; set; }

    public virtual Employees Employee { get; set; }

    public virtual Orders Order { get; set; }
}