// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class OrdersReceivedArticlesResult
    {
        public int? ORDERID { get; set; }
        public int? ARTID { get; set; }
        [StringLength(100)]
        public string ArtNr { get; set; }
        [StringLength(100)]
        public string ArtDescription { get; set; }
        [StringLength(20)]
        public string ArtUnit { get; set; }
        public double? Quantity { get; set; }
    }
}
