// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class OrdersUnscheduledTasks
{
    public int Id { get; set; }

    public int OrderId { get; set; }

    public int UnscheduledTaskId { get; set; }

    public double? Amount { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual Orders Order { get; set; }

    public virtual ICollection<ReceivingArticlesPositions2> ReceivingArticlesPositions2 { get; set; } = new List<ReceivingArticlesPositions2>();

    public virtual ICollection<SuppliersInvoicesOrdersUnscheduledTasks> SuppliersInvoicesOrdersUnscheduledTasks { get; set; } = new List<SuppliersInvoicesOrdersUnscheduledTasks>();

    public virtual UnscheduledTasks UnscheduledTask { get; set; }
}