// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class PComponentsListResult
    {
        public int ID { get; set; }
        [StringLength(500)]
        public string Name1 { get; set; }
        [StringLength(500)]
        public string Name2 { get; set; }
        public int? CounterID { get; set; }
        [StringLength(500)]
        public string SerialNr { get; set; }
        [StringLength(500)]
        public string TypeNr { get; set; }
        public int? ParentID { get; set; }
        public int? ClassID { get; set; }
        [StringLength(500)]
        public string TagNr { get; set; }
        public int? Position { get; set; }
        public int? GroupArtID { get; set; }
        public bool? IsComponent { get; set; }
        public bool? Inactive { get; set; }
        [StringLength(2147483647)]
        public string Description { get; set; }
        public int? ArtID { get; set; }
        public bool? Critical { get; set; }
        [StringLength(500)]
        public string SFI2 { get; set; }
        public int? ManufacturerID { get; set; }
        public int? RefComponentID { get; set; }
        public byte[] TimeStamp { get; set; }
        [StringLength(1000)]
        public string Location1 { get; set; }
        public int? VoninID { get; set; }
        public double? MonthlyRentPrice { get; set; }
        public byte[] Image { get; set; }
        public int? VoninParentID { get; set; }
        public DateTime? Date { get; set; }
        public int? SupplierID { get; set; }
        [StringLength(500)]
        public string Specification { get; set; }
        public byte[] ImageThumbnail { get; set; }
        [StringLength(100)]
        public string field1 { get; set; }
        [StringLength(100)]
        public string field2 { get; set; }
        [StringLength(100)]
        public string field3 { get; set; }
        [StringLength(100)]
        public string field4 { get; set; }
        [StringLength(100)]
        public string field5 { get; set; }
        [StringLength(100)]
        public string field6 { get; set; }
        [StringLength(5000)]
        public string ComponentTree { get; set; }
    }
}
