// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class PGetComponentTasksIntervalsResult
    {
        public int? EmployeeID { get; set; }
        public int? TaskIntervalsID { get; set; }
        public int? IntervalRoleID { get; set; }
        public double? RunningHours { get; set; }
        public DateTime? NextLogDate { get; set; }
        public double? LeftTime { get; set; }
        [StringLength(2000)]
        public string LeftTimeChar { get; set; }
        [StringLength(5000)]
        public string IntervalChar { get; set; }
        public int? TaskIntervalID { get; set; }
        public int? TaskID { get; set; }
        public int? TaskTypeID { get; set; }
        public int? Interval { get; set; }
        public int? IntervalTypeID { get; set; }
        public int? LastTaskLogID { get; set; }
        public int? TaskRoleID { get; set; }
        public DateOnly? CreateDate { get; set; }
        public int? NrDaysAccomplishBeforeNextDate { get; set; }
        public byte[] TimeStamp { get; set; }
        public int? AssignedToUserID { get; set; }
        public bool? Priority { get; set; }
        public double? NrDaysOrHoursPostponed { get; set; }
        public double? PreviousNrDaysOrHoursPostponed { get; set; }
        public int? VoninID { get; set; }
        [StringLength(50)]
        public string TaskType { get; set; }
        public int Weight { get; set; }
    }
}
