// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class PGetTaskFieldsResult
    {
        [StringLength(100)]
        public string FIELD1 { get; set; }
        [StringLength(100)]
        public string FIELD2 { get; set; }
        [StringLength(100)]
        public string FIELD3 { get; set; }
        [StringLength(100)]
        public string FIELD4 { get; set; }
        [StringLength(100)]
        public string FIELD5 { get; set; }
        [StringLength(100)]
        public string FIELD6 { get; set; }
        [StringLength(100)]
        public string FIELD7 { get; set; }
    }
}
