// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class PSelectExportConsumingArticlesResult
    {
        public int KontuNr { get; set; }
        [StringLength(20)]
        public string BokingarDagur { get; set; }
        [StringLength(100)]
        public string SkjalaNr { get; set; }
        [StringLength(500)]
        public string BokingarTekstur { get; set; }
        public int MotKontuNr { get; set; }
        [Column("Upphadd", TypeName = "decimal(10,3)")]
        public decimal? Upphadd { get; set; }
        [StringLength(11)]
        public string DimensjonEitt { get; set; }
        [StringLength(500)]
        public string DimensjonTvey { get; set; }
        public int DimensjonTri { get; set; }
        [StringLength(1)]
        public string DimensjonFyra { get; set; }
    }
}
