// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class PTaskFieldDataResult
    {
        public int TaskFieldID { get; set; }
        [StringLength(50)]
        public string FieldPrompt { get; set; }
        [StringLength(50)]
        public string FieldUnit { get; set; }
        public int? FieldTypeID { get; set; }
        public double? MinValue { get; set; }
        public double? MaxValue { get; set; }
        public int? TaskClassID { get; set; }
        public int? TaskFieldDataID { get; set; }
        public int? TaskLogID { get; set; }
        [StringLength(50)]
        public string FieldData { get; set; }
    }
}
