// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class Purchases
{
    public int Id { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public int? EmployeeId { get; set; }

    public string Note { get; set; }

    public int? FileId { get; set; }

    public bool? Processed { get; set; }

    public int? ProcessedById { get; set; }

    public DateTime? ProcessedDate { get; set; }

    public int? ComponentId { get; set; }

    public int? UnscheduledTaskId { get; set; }

    public byte[] TimeStamp { get; set; }

    public int? TaskLogId { get; set; }

    public virtual ICollection<BarcodereaderSessions> BarcodereaderSessions { get; set; } = new List<BarcodereaderSessions>();

    public virtual Components Component { get; set; }

    public virtual ICollection<ConsumingArticles> ConsumingArticles { get; set; } = new List<ConsumingArticles>();

    public virtual Employees Employee { get; set; }

    public virtual Employees ProcessedBy { get; set; }

    public virtual TaskLogs TaskLog { get; set; }

    public virtual UnscheduledTasks UnscheduledTask { get; set; }
}