// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class PWEBScheduledUnscheduledTasksResult
    {
        [StringLength(1000)]
        public string Title { get; set; }
        public int? TaskID { get; set; }
        public int? TaskIntID { get; set; }
        public int? TaskTypeID { get; set; }
        public double? LeftTime { get; set; }
        [StringLength(2000)]
        public string LeftTimeChar { get; set; }
        public DateTime? NextDate { get; set; }
        public int? IntervalTypeID { get; set; }
        [StringLength(5000)]
        public string IntervalChar { get; set; }
        public DateTime? CompletedTime { get; set; }
        [StringLength(2031)]
        public string TotalLeftTimeChar { get; set; }
    }
}
