// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class Racks
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int StockId { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual ICollection<ArticlesDefaultStocks> ArticlesDefaultStocks { get; set; } = new List<ArticlesDefaultStocks>();

    public virtual ICollection<CheckingStocksSelectedRacks> CheckingStocksSelectedRacks { get; set; } = new List<CheckingStocksSelectedRacks>();

    public virtual ICollection<Shelves> Shelves { get; set; } = new List<Shelves>();

    public virtual StocksList Stock { get; set; }
}