// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class ReceivingArticlesHeader
{
    public int Id { get; set; }

    public int? OrderId { get; set; }

    public int? InternalNr { get; set; }

    public int? ReceivedById { get; set; }

    public bool? Closed { get; set; }

    public DateTime? Date { get; set; }

    public int? StockId { get; set; }

    public string Note { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual Orders Order { get; set; }

    public virtual Employees ReceivedBy { get; set; }

    public virtual ICollection<ReceivingArticlesPositions> ReceivingArticlesPositions { get; set; } = new List<ReceivingArticlesPositions>();

    public virtual ICollection<ReceivingArticlesPositions2> ReceivingArticlesPositions2 { get; set; } = new List<ReceivingArticlesPositions2>();

    public virtual StocksList Stock { get; set; }
}