// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class ReceivingArticlesPositions
{
    public int Id { get; set; }

    public int? OrdersArticleId { get; set; }

    public int? ReceivingArticlesHeaderId { get; set; }

    public int? ArtId { get; set; }

    public double? Quantity { get; set; }

    public int? ShelveId { get; set; }

    public bool? DirectToConsumption { get; set; }

    public string DepartId { get; set; }

    public double? Price { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual Articles Art { get; set; }

    public virtual OrdersArticles OrdersArticle { get; set; }

    public virtual ReceivingArticlesHeader ReceivingArticlesHeader { get; set; }

    public virtual Shelves Shelve { get; set; }
}