// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class ReportContainerComponentsPrKundaResult
    {
        public int? ID1 { get; set; }
        public int? ID2 { get; set; }
        [StringLength(500)]
        public string Name1 { get; set; }
        [StringLength(500)]
        public string Bingja { get; set; }
        [StringLength(500)]
        public string Eigari { get; set; }
    }
}
