// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class ReportStocks_OLDResult
    {
        [StringLength(50)]
        public string Nr { get; set; }
        [StringLength(500)]
        public string Description { get; set; }
        public double? QUANTITY { get; set; }
        public double? CostPrice { get; set; }
        [StringLength(50)]
        public string ShortName { get; set; }
        public double? ArtValue { get; set; }
        [StringLength(10)]
        public string Unit { get; set; }
        public double? StockMin { get; set; }
        [StringLength(500)]
        public string Art { get; set; }
        [StringLength(50)]
        public string GroupOfArt { get; set; }
    }
}
