// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class ReportFolder
{
    public int? ReportServerId { get; set; }

    public int ReportFolderId { get; set; }

    public string FolderName { get; set; }

    public virtual ICollection<Report> Report { get; set; } = new List<Report>();

    public virtual ReportServer ReportServer { get; set; }
}