// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class ReportStocksRacksShelvesResult
    {
        public int ID { get; set; }
        [StringLength(50)]
        public string ShortName { get; set; }
        [StringLength(100)]
        public string Name { get; set; }
        [StringLength(500)]
        public string Adress { get; set; }
        public byte[] TimeStamp { get; set; }
        [StringLength(20)]
        public string RackName { get; set; }
        [StringLength(20)]
        public string ShelveName { get; set; }
    }
}
