// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class ReportOrders_OrdersResult
    {
        public int ID { get; set; }
        public int? OrderNr { get; set; }
        [StringLength(100)]
        public string Description { get; set; }
        public int? SupplID { get; set; }
        public DateTime? CreateDate { get; set; }
        public DateTime? CompleteDate { get; set; }
        public DateTime? DeliveryDate { get; set; }
        public bool? OrderedByPhone { get; set; }
        [StringLength(100)]
        public string DepartID { get; set; }
        public int? AccountID { get; set; }
        public int OurPersonID { get; set; }
        public int SupplPersonID { get; set; }
        public int? CreateUserID { get; set; }
        public double? Value { get; set; }
        [StringLength(5)]
        public string Currency { get; set; }
        public bool? Printed { get; set; }
        public DateTime? Regtime { get; set; }
        [StringLength(50)]
        public string EmployeeName { get; set; }
        [StringLength(100)]
        public string ContactName { get; set; }
        public int? AccountNr { get; set; }
        [StringLength(100)]
        public string SupplierName { get; set; }
        [StringLength(100)]
        public string SupplAdress1 { get; set; }
        [StringLength(100)]
        public string SupplAdress2 { get; set; }
        [StringLength(100)]
        public string SupplAdress4 { get; set; }
        [StringLength(100)]
        public string SupplAdress3 { get; set; }
        [StringLength(30)]
        public string SupplPhone { get; set; }
        [StringLength(30)]
        public string SupplFax { get; set; }
        public bool? UrgentDelivery { get; set; }
        [StringLength(500)]
        public string CompSerialNr { get; set; }
        [StringLength(500)]
        public string CompTypeNr { get; set; }
        [StringLength(2147483647)]
        public string CompDescription { get; set; }
        [StringLength(150)]
        public string CountryName { get; set; }
        [StringLength(100)]
        public string EmployeeEmail { get; set; }
        public int? CompanyDeliveryAddressID { get; set; }
        [StringLength(1000)]
        public string DeliveryAddress { get; set; }
        [StringLength(50)]
        public string AccountName { get; set; }
        [StringLength(100)]
        public string DepartmentName { get; set; }
        public byte[] Signature { get; set; }
    }
}
