// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class Report
{
    public int ReportFolderId { get; set; }

    public int ReportId { get; set; }

    public string NameOnClient { get; set; }

    public string NameOnServer { get; set; }

    public int? ModuleId { get; set; }

    public string Tab { get; set; }

    public string Name { get; set; }

    public string ToolTip { get; set; }

    public bool? IsExtraReport { get; set; }

    public string GroupName { get; set; }

    public bool? Landscape { get; set; }

    public int? ApplicationViewId { get; set; }

    public bool? PrintLayoutDefault { get; set; }

    public bool? HasConfigurablePrinter { get; set; }

    public bool? AskForQuantity { get; set; }

    public string ChildRowDbtableName { get; set; }

    public string DirectToEmail { get; set; }

    public string DirectToEmailSubject { get; set; }

    public bool LogPrintEvent { get; set; }

    public virtual ApplicationView ApplicationView { get; set; }

    public virtual ReportFolder ReportFolder { get; set; }
}