// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class ReportConsumedArticlesResult
    {
        public int ID { get; set; }
        public int? ArtID { get; set; }
        public int? ShelveID { get; set; }
        public DateTime? Date { get; set; }
        public int? UserID { get; set; }
        public double? Quantity { get; set; }
        [StringLength(100)]
        public string DepartID { get; set; }
        public int? PurchaseID { get; set; }
        public double? ArtCostPrice { get; set; }
        [StringLength(100)]
        public string Nr { get; set; }
        [StringLength(500)]
        public string Description { get; set; }
        [StringLength(63)]
        public string UnscheduledTask { get; set; }
        [StringLength(500)]
        public string Component { get; set; }
        [StringLength(50)]
        public string Employee { get; set; }
        [StringLength(1000)]
        public string TaskName { get; set; }
        [StringLength(20)]
        public string Shelve { get; set; }
        [StringLength(20)]
        public string Rack { get; set; }
        [StringLength(50)]
        public string Stock { get; set; }
        [StringLength(2147483647)]
        public string Art { get; set; }
        [StringLength(500)]
        public string ComponentClass { get; set; }
    }
}
