// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class ReportCheckingStocksHeaderResult
    {
        public DateTime? Date { get; set; }
        public bool? Closed { get; set; }
        [StringLength(50)]
        public string CheckedBy { get; set; }
        [StringLength(50)]
        public string Stock { get; set; }
    }
}
