// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class ReportServer
{
    public int ReportServerId { get; set; }

    public string ServerPath { get; set; }

    public string ServerDescription { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public virtual ICollection<ReportFolder> ReportFolder { get; set; } = new List<ReportFolder>();
}