// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class ReportAllSubComponentsWithDataVONINFinnurFriResult
    {
        public int? compID { get; set; }
        public int? ID { get; set; }
        [StringLength(5000)]
        public string C1 { get; set; }
        [StringLength(5000)]
        public string C2 { get; set; }
        [StringLength(5000)]
        public string C3 { get; set; }
        [StringLength(5000)]
        public string C4 { get; set; }
        [StringLength(5000)]
        public string C5 { get; set; }
        [StringLength(5000)]
        public string C6 { get; set; }
        [StringLength(5000)]
        public string C7 { get; set; }
        [StringLength(5000)]
        public string C8 { get; set; }
        [StringLength(500)]
        public string Name1 { get; set; }
        public int? ClassID { get; set; }
        public int? ParentID { get; set; }
        public bool? IsComponent { get; set; }
        public byte[] Image { get; set; }
    }
}
