// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class ReportSuppliersResult
    {
        public int ID { get; set; }
        [StringLength(100)]
        public string Name { get; set; }
        [StringLength(403)]
        public string Address { get; set; }
        [StringLength(150)]
        public string Country { get; set; }
        [StringLength(30)]
        public string Phone { get; set; }
        [StringLength(100)]
        public string Email { get; set; }
        [StringLength(200)]
        public string WebSite { get; set; }
    }
}
