// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class ReportOrders_OrdersArticlesResult
    {
        public int ID { get; set; }
        public int? Position { get; set; }
        public int OrderID { get; set; }
        public int? ArtID { get; set; }
        public double? Quantity { get; set; }
        [StringLength(20)]
        public string Unit { get; set; }
        [StringLength(100)]
        public string Description { get; set; }
        [StringLength(30)]
        public string Quant_char { get; set; }
        [StringLength(30)]
        public string Received { get; set; }
        public double? Price { get; set; }
        public double? Discount { get; set; }
        public byte[] Timestamp { get; set; }
        public double? TotalPrice { get; set; }
        [StringLength(100)]
        public string Nr { get; set; }
        [StringLength(100)]
        public string ManufacturerArtNr { get; set; }
        public string Memo { get; set; }
        [StringLength(200)]
        public string ManufacturerName { get; set; }
        [StringLength(2147483647)]
        public string SupplierArtNr { get; set; }
        [StringLength(500)]
        public string SerialNr { get; set; }
        [StringLength(500)]
        public string TypeNr { get; set; }
        [StringLength(2147483647)]
        public string CompDescription { get; set; }
        public int ComponentID { get; set; }
        [StringLength(2147483647)]
        public string ComponentDetails { get; set; }
    }
}
