// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class ReportCheckingStocksPositionsResult
    {
        public int ID { get; set; }
        public int? CheckingStocks_HeaderID { get; set; }
        public int? ArtID { get; set; }
        public int? ShelveID { get; set; }
        public double? OnStockQuantity { get; set; }
        public double? CountedQuantity { get; set; }
        public byte[] TimeStamp { get; set; }
        public int? OldShelveID { get; set; }
        [StringLength(100)]
        public string Nr { get; set; }
        [StringLength(500)]
        public string Description { get; set; }
        [StringLength(20)]
        public string Shelve { get; set; }
        [StringLength(20)]
        public string Rack { get; set; }
    }
}
