// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class ReportArticlesForACertainStockResult
    {
        public int ID { get; set; }
        [StringLength(100)]
        public string Nr { get; set; }
        [StringLength(500)]
        public string Description { get; set; }
        [StringLength(50)]
        public string Description2 { get; set; }
        [StringLength(50)]
        public string SearchText { get; set; }
        public double? StockMin { get; set; }
        public double? QuantityDef { get; set; }
        public double? SalePrice { get; set; }
        public double? CostPrice { get; set; }
        public int? UnitID { get; set; }
        public bool? Inactive { get; set; }
        public int? CreateUserID { get; set; }
        public DateOnly? CreateDate { get; set; }
        public string Memo { get; set; }
        public int? ManufacturerID { get; set; }
        public int? MaterialID { get; set; }
        public double? Length { get; set; }
        public double? Width { get; set; }
        public double? Height { get; set; }
        public double? Weight { get; set; }
        [StringLength(50)]
        public string CustomsTariffNr { get; set; }
        public byte[] TimeStamp { get; set; }
        public int? CurrencyID { get; set; }
        public bool? NoStock { get; set; }
        [StringLength(100)]
        public string ManufacturerArtNr { get; set; }
        [StringLength(50)]
        public string DefaultOrMaxStockLabel { get; set; }
        public double? CurrentPrice { get; set; }
        [StringLength(5)]
        public string UM { get; set; }
        public double? TotalStockQuantity { get; set; }
    }
}
