// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class ReportCountersResult
    {
        public int ID { get; set; }
        [StringLength(300)]
        public string Counter { get; set; }
        [StringLength(300)]
        public string TagName { get; set; }
        public bool? Inactive { get; set; }
        public double? HoursPerDay { get; set; }
        public double? Hours { get; set; }
    }
}
