// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class ResourcesTable
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual ICollection<Expenses> Expenses { get; set; } = new List<Expenses>();
}