// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class Roles
{
    public int Id { get; set; }

    public string ShortName { get; set; }

    public string Name { get; set; }

    public bool? Inactive { get; set; }

    public byte[] TimeStamp { get; set; }

    public string UnscheduledTasksEmails { get; set; }

    public string Comments { get; set; }

    public int? VoninId { get; set; }

    public virtual ICollection<ComponentAccess> ComponentAccess { get; set; } = new List<ComponentAccess>();

    public virtual ICollection<ComponentRoles> ComponentRoles { get; set; } = new List<ComponentRoles>();

    public virtual ICollection<EmployeesRoleApplicationView> EmployeesRoleApplicationView { get; set; } = new List<EmployeesRoleApplicationView>();

    public virtual ICollection<EmployeesRoles> EmployeesRoles { get; set; } = new List<EmployeesRoles>();

    public virtual ICollection<Notifications> Notifications { get; set; } = new List<Notifications>();

    public virtual ICollection<TaskIntervals> TaskIntervals { get; set; } = new List<TaskIntervals>();

    public virtual ICollection<TaskLogsList> TaskLogsList { get; set; } = new List<TaskLogsList>();

    public virtual ICollection<UnscheduledTasks> UnscheduledTasksCreatedRole { get; set; } = new List<UnscheduledTasks>();

    public virtual ICollection<UnscheduledTasks> UnscheduledTasksResponsibleRole { get; set; } = new List<UnscheduledTasks>();
}