// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class SelectScheduledUnscheduledTasks_ByLaurResult
    {
        [StringLength(5)]
        public string Unscheduled { get; set; }
        public int ID { get; set; }
        public int? TaskIntervalsID { get; set; }
        public int? TaskLogsListID { get; set; }
        public int? TASKID { get; set; }
        public double? RunningHours { get; set; }
        public int? UserID { get; set; }
        public int? ComponentID { get; set; }
        [StringLength(1000)]
        public string TaskName { get; set; }
        public string TaskDescription { get; set; }
        [StringLength(5000)]
        public string ComponentTree { get; set; }
        public DateTime? completedTime { get; set; }
        [StringLength(50)]
        public string Format_CompletedTime { get; set; }
        public int? TaskTypeID { get; set; }
        [StringLength(50)]
        public string TaskTypeShortName { get; set; }
        public double? LeftTime { get; set; }
        [StringLength(2000)]
        public string LeftTimeChar { get; set; }
        public DateTime? NextDate { get; set; }
        [StringLength(50)]
        public string Format_NextDate { get; set; }
        public double? Hours { get; set; }
        public string action { get; set; }
    }
}
