// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class SelectNotificationsResult
    {
        public int? ID { get; set; }
        public int? NotificationID { get; set; }
        [StringLength(2147483647)]
        public string Description { get; set; }
        public DateTime? Date { get; set; }
        public int? UserID { get; set; }
        [StringLength(100)]
        public string UserShName { get; set; }
        [StringLength(100)]
        public string Title { get; set; }
        public int? Nr { get; set; }
        public int? CreatedRoleID { get; set; }
        public int? ResponsibleRoleID { get; set; }
        public int? NotificationTypeID { get; set; }
        public int? ComponentID { get; set; }
        public bool? Priority { get; set; }
        public bool? OnHold { get; set; }
        public DateTime? Deadline { get; set; }
        [StringLength(2147483647)]
        public string Action { get; set; }
        public DateTime? CompletedTime { get; set; }
        public int? CompletedUserID { get; set; }
        public double? ComponentHours { get; set; }
        public DateTime? CompletedTimeNull { get; set; }
        public int? LeftTime { get; set; }
        [StringLength(50)]
        public string LeftTimeChar { get; set; }
        [StringLength(30)]
        public string UnscheduledTask_Notif { get; set; }
        public int? NrDoc { get; set; }
        [StringLength(50)]
        public string AssignedToUserShName { get; set; }
    }
}
