// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class SelectScheduledUnscheduledTasksNextPreviousWeekResult
    {
        public int Unscheduled { get; set; }
        public int ID { get; set; }
        public int? TaskIntervalsID { get; set; }
        public int? TaskLogsListID { get; set; }
        public int TASKID { get; set; }
        public int? TaskTypeID { get; set; }
        public double? RunningHours { get; set; }
        public int? UserID { get; set; }
        public int? ComponentID { get; set; }
        [StringLength(1000)]
        public string TaskName { get; set; }
        public int TaskClassID { get; set; }
        public string TaskDescription { get; set; }
        [StringLength(5000)]
        public string ComponentTree { get; set; }
        public DateTime? completedTime { get; set; }
        [StringLength(500)]
        public string TaskTypeName { get; set; }
        public double? LeftTime { get; set; }
        [StringLength(2000)]
        public string LeftTimeChar { get; set; }
        public DateTime? NextLogDate { get; set; }
        [StringLength(5000)]
        public string IntervalChar { get; set; }
        public double? Hours { get; set; }
        public string action { get; set; }
        public bool? Priority { get; set; }
        [StringLength(50)]
        public string UserShName { get; set; }
        public int NrDoc { get; set; }
        public int NrArt { get; set; }
        public int NrRemarks { get; set; }
        [StringLength(100)]
        public string FileTitle { get; set; }
        public DateTime? CreateDate { get; set; }
        public int? CreateUserID { get; set; }
    }
}
