// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class Shelves
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int RackId { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual ICollection<ArticlesDefaultStocks> ArticlesDefaultStocks { get; set; } = new List<ArticlesDefaultStocks>();

    public virtual ICollection<ArticlesIn> ArticlesIn { get; set; } = new List<ArticlesIn>();

    public virtual ICollection<CheckingStocksPositions> CheckingStocksPositionsOldShelve { get; set; } = new List<CheckingStocksPositions>();

    public virtual ICollection<CheckingStocksPositions> CheckingStocksPositionsShelve { get; set; } = new List<CheckingStocksPositions>();

    public virtual ICollection<CheckingStocksSelectedShelves> CheckingStocksSelectedShelves { get; set; } = new List<CheckingStocksSelectedShelves>();

    public virtual ICollection<ConsumingArticles> ConsumingArticles { get; set; } = new List<ConsumingArticles>();

    public virtual ICollection<MovingArticlesPositions> MovingArticlesPositionsShelveid1Navigation { get; set; } = new List<MovingArticlesPositions>();

    public virtual ICollection<MovingArticlesPositions> MovingArticlesPositionsShelveid2Navigation { get; set; } = new List<MovingArticlesPositions>();

    public virtual ICollection<OrdersLocationsHistory> OrdersLocationsHistory { get; set; } = new List<OrdersLocationsHistory>();

    public virtual Racks Rack { get; set; }

    public virtual ICollection<ReceivingArticlesPositions> ReceivingArticlesPositions { get; set; } = new List<ReceivingArticlesPositions>();

    public virtual ICollection<StocksHistory> StocksHistory { get; set; } = new List<StocksHistory>();

    public virtual ICollection<UnscheduledTaskNeededArticles> UnscheduledTaskNeededArticles { get; set; } = new List<UnscheduledTaskNeededArticles>();
}