// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class SpXama_LookupComponentsResult
    {
        public int? ID { get; set; }
        [StringLength(2147483647)]
        public string ComponentName { get; set; }
        public byte[] IconImage { get; set; }
        public int? ParentId { get; set; }
        public bool? IsHeader { get; set; }
        public int? ClassId { get; set; }
        public int? Position { get; set; }
    }
}
