// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class SpXama_ComponentClassFieldsResult
    {
        public int? ColumnNr { get; set; }
        public int? FieldNr { get; set; }
        [StringLength(50)]
        public string FieldPrompt { get; set; }
        [StringLength(5000)]
        public string FieldData { get; set; }
        [StringLength(50)]
        public string FieldUnit { get; set; }
    }
}
