// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class SpXama_ComponentTasksResult
    {
        public int ID { get; set; }
        [StringLength(1000)]
        public string Name { get; set; }
        [StringLength(5000)]
        public string Description { get; set; }
        public double? LeftTime { get; set; }
        public DateTime? NextDate { get; set; }
        [StringLength(5000)]
        public string IntervalChar { get; set; }
        public int? TaskClassID { get; set; }
        [StringLength(100)]
        public string TaskClassName { get; set; }
        public int? IntervalTypeID { get; set; }
        public int? TaskTypeID { get; set; }
        public int? TaskIntervalId { get; set; }
    }
}
