// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class SpXama_ComponentDetailsResult
    {
        public int ID { get; set; }
        [StringLength(500)]
        public string Name1 { get; set; }
        [StringLength(500)]
        public string Name2 { get; set; }
        [StringLength(500)]
        public string TagNr { get; set; }
        [StringLength(500)]
        public string SFI2 { get; set; }
        [StringLength(500)]
        public string SerialNr { get; set; }
        [StringLength(500)]
        public string TypeNr { get; set; }
        public byte[] Image { get; set; }
        [StringLength(5000)]
        public string ComponentTree { get; set; }
        [StringLength(5000)]
        public string ComponentReferences { get; set; }
        public bool? ShowSFI { get; set; }
        public int? ParentID { get; set; }
    }
}
