// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class StocksList
{
    public int Id { get; set; }

    public string ShortName { get; set; }

    public string Name { get; set; }

    public string Adress { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual ICollection<ArticlesDefaultStocks> ArticlesDefaultStocks { get; set; } = new List<ArticlesDefaultStocks>();

    public virtual ICollection<ArticlesStocksMinimumDefaultQuantity> ArticlesStocksMinimumDefaultQuantity { get; set; } = new List<ArticlesStocksMinimumDefaultQuantity>();

    public virtual ICollection<CheckingStocksHeader> CheckingStocksHeader { get; set; } = new List<CheckingStocksHeader>();

    public virtual ICollection<MovingArticlesHeader> MovingArticlesHeaderStockid1Navigation { get; set; } = new List<MovingArticlesHeader>();

    public virtual ICollection<MovingArticlesHeader> MovingArticlesHeaderStockid2Navigation { get; set; } = new List<MovingArticlesHeader>();

    public virtual ICollection<Racks> Racks { get; set; } = new List<Racks>();

    public virtual ICollection<ReceivingArticlesHeader> ReceivingArticlesHeader { get; set; } = new List<ReceivingArticlesHeader>();
}