// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class StocksEvidence
{
    public int Id { get; set; }

    public int? ArtId { get; set; }

    public int? ShelveId { get; set; }

    public double? Quantity { get; set; }

    public DateTime? Date { get; set; }

    public byte[] TimeStamp { get; set; }

    public bool? NewLocation { get; set; }

    public double? CostPrice { get; set; }

    public int? EmployeeId { get; set; }

    public int? CurrencyId { get; set; }

    public double? ExchangeRate { get; set; }

    public virtual Articles Art { get; set; }

    public virtual Currencies Currency { get; set; }

    public virtual Employees Employee { get; set; }
}