// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class Suppliers
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Adress1 { get; set; }

    public string Adress2 { get; set; }

    public string Adress3 { get; set; }

    public string Adress4 { get; set; }

    public int? CountryId { get; set; }

    public string Phone { get; set; }

    public string Fax { get; set; }

    public string Memo { get; set; }

    public int? Account { get; set; }

    public string Email { get; set; }

    public bool? Inactive { get; set; }

    public string PostalCode { get; set; }

    public byte[] TimeStamp { get; set; }

    public bool? Shipper { get; set; }

    public string WebSite { get; set; }

    public virtual ICollection<ComponentSuppliers> ComponentSuppliers { get; set; } = new List<ComponentSuppliers>();

    public virtual ICollection<Components> Components { get; set; } = new List<Components>();

    public virtual Countries Country { get; set; }

    public virtual ICollection<Orders> OrdersShipper { get; set; } = new List<Orders>();

    public virtual ICollection<Orders> OrdersSuppl { get; set; } = new List<Orders>();

    public virtual ICollection<SuppliersContacts> SuppliersContacts { get; set; } = new List<SuppliersContacts>();

    public virtual ICollection<SuppliersDocuments> SuppliersDocuments { get; set; } = new List<SuppliersDocuments>();

    public virtual ICollection<SuppliersGroupsOfSuppliers> SuppliersGroupsOfSuppliers { get; set; } = new List<SuppliersGroupsOfSuppliers>();

    public virtual ICollection<SuppliersInvoices> SuppliersInvoices { get; set; } = new List<SuppliersInvoices>();
}