// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class SuppliersInvoicesEvents
{
    public int Id { get; set; }

    public int? SuppliersInvoiceId { get; set; }

    public DateTime? EventTime { get; set; }

    public int? CreatedEmployeeId { get; set; }

    public int? ToEmployeeId { get; set; }

    public int? InvoiceEventTypeId { get; set; }

    public string Note { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual Employees CreatedEmployee { get; set; }

    public virtual InvoiceEventTypes InvoiceEventType { get; set; }

    public virtual SuppliersInvoices SuppliersInvoice { get; set; }

    public virtual Employees ToEmployee { get; set; }
}