// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class SuppliersInvoicesOrdersArticles
{
    public int Id { get; set; }

    public int? SuppliersInvoiceId { get; set; }

    public int? OrdersArticleId { get; set; }

    public double? Amount { get; set; }

    public double? Price { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual OrdersArticles OrdersArticle { get; set; }

    public virtual SuppliersInvoices SuppliersInvoice { get; set; }
}