// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class SuppliersInvoices
{
    public int Id { get; set; }

    public int? OrderId { get; set; }

    public string Nr { get; set; }

    public DateTime? Date { get; set; }

    public double? Value { get; set; }

    public bool? Closed { get; set; }

    public string Note { get; set; }

    public int? SupplierId { get; set; }

    public int? AccountId { get; set; }

    public int? LastInvoiceEventId { get; set; }

    public string SupplierNotDb { get; set; }

    public int? FileId { get; set; }

    public bool? Deleted { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual Accounts Account { get; set; }

    public virtual ICollection<Expenses> Expenses { get; set; } = new List<Expenses>();

    public virtual FilesTable File { get; set; }

    public virtual Orders Order { get; set; }

    public virtual Suppliers Supplier { get; set; }

    public virtual ICollection<SuppliersInvoicesDocuments> SuppliersInvoicesDocuments { get; set; } = new List<SuppliersInvoicesDocuments>();

    public virtual ICollection<SuppliersInvoicesEvents> SuppliersInvoicesEvents { get; set; } = new List<SuppliersInvoicesEvents>();

    public virtual ICollection<SuppliersInvoicesOrdersArticles> SuppliersInvoicesOrdersArticles { get; set; } = new List<SuppliersInvoicesOrdersArticles>();

    public virtual ICollection<SuppliersInvoicesOrdersUnscheduledTasks> SuppliersInvoicesOrdersUnscheduledTasks { get; set; } = new List<SuppliersInvoicesOrdersUnscheduledTasks>();
}