// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class SuppliersContacts
{
    public int Id { get; set; }

    public int SupplId { get; set; }

    public string Name { get; set; }

    public string Phone { get; set; }

    public string Info { get; set; }

    public string Email { get; set; }

    public byte[] TimeStamp { get; set; }

    public Guid? SynchId { get; set; }

    public bool? Inactive { get; set; }

    public virtual ICollection<Orders> OrdersShipperPerson { get; set; } = new List<Orders>();

    public virtual ICollection<Orders> OrdersSupplPerson { get; set; } = new List<Orders>();

    public virtual Suppliers Suppl { get; set; }
}