// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class SynchIdMap
{
    public int Id { get; set; }

    public string SourceDbName { get; set; }

    public string TableName { get; set; }

    public int SourceId { get; set; }

    public int TargetId { get; set; }
}