// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class T12
{
    public int Id { get; set; }

    public string Nr { get; set; }

    public string Description { get; set; }

    public string Description2 { get; set; }

    public string SearchText { get; set; }

    public double? StockMin { get; set; }

    public double? QuantityDef { get; set; }

    public double? SalePrice { get; set; }

    public double? CostPrice { get; set; }

    public int? UnitId { get; set; }

    public bool? Inactive { get; set; }

    public int? CreateUserId { get; set; }

    public DateOnly? CreateDate { get; set; }

    public string Memo { get; set; }

    public int? ManufacturerId { get; set; }

    public int? MaterialId { get; set; }

    public double? Length { get; set; }

    public double? Width { get; set; }

    public double? Height { get; set; }

    public double? Weight { get; set; }

    public string CustomsTariffNr { get; set; }

    public byte[] TimeStamp { get; set; }

    public int? CurrencyId { get; set; }

    public bool? NoStock { get; set; }

    public string ManufacturerArtNr { get; set; }

    public string DefaultOrMaxStockLabel { get; set; }

    public string Name { get; set; }

    public string SupplArtNr { get; set; }
}