// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class TableFieldData
{
    public int Id { get; set; }

    public int TableFieldId { get; set; }

    public int ColumnId { get; set; }

    public string FieldData { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual TableFields TableField { get; set; }
}