// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class TableFields
{
    public int Id { get; set; }

    public string FieldPrompt { get; set; }

    public int? FieldTypeId { get; set; }

    public string FieldUnit { get; set; }

    public int? FieldNr { get; set; }

    public int? ColumnNr { get; set; }

    public string FieldToolTipText { get; set; }

    public double? MinValue { get; set; }

    public double? MaxValue { get; set; }

    public int? TableId { get; set; }

    public byte[] TimeStamp { get; set; }

    public int? NotificationTypeId { get; set; }

    public virtual FieldsTypes FieldType { get; set; }

    public virtual NotificationTypes NotificationType { get; set; }

    public virtual ICollection<TableFieldComboBoxValues> TableFieldComboBoxValues { get; set; } = new List<TableFieldComboBoxValues>();

    public virtual ICollection<TableFieldData> TableFieldData { get; set; } = new List<TableFieldData>();
}