// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class Tables
{
    public string TableName { get; set; }

    public int? LastTimeStampInt { get; set; }

    /// <summary>
    /// Not PK, not autoincremented. Used for Modules with extended fields
    /// </summary>
    public int? Id { get; set; }

    public string ModuleName { get; set; }
}