// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class TaskIntervalsStoppedRestarted
{
    public int Id { get; set; }

    public int? TaskIntervalId { get; set; }

    public bool? StoppedRestarted { get; set; }

    public DateTime? StoppedRestartedTime { get; set; }

    public int? UserId { get; set; }

    public int? NrPassedDaysHours { get; set; }

    public virtual TaskIntervals TaskInterval { get; set; }

    public virtual Employees User { get; set; }
}