// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class TaskFields
{
    public int Id { get; set; }

    public string FieldPrompt { get; set; }

    public int? FieldTypeId { get; set; }

    public string FieldUnit { get; set; }

    public int? FieldNr { get; set; }

    public int? ColumnNr { get; set; }

    public string FieldToolTipText { get; set; }

    public double? MinValue { get; set; }

    public double? MaxValue { get; set; }

    public int? TaskClassId { get; set; }

    public byte[] TimeStamp { get; set; }

    public string Heading { get; set; }

    public virtual ICollection<AccomplishData> AccomplishData { get; set; } = new List<AccomplishData>();

    public virtual FieldsTypes FieldType { get; set; }

    public virtual TaskClasses TaskClass { get; set; }

    public virtual ICollection<TaskFieldComboBoxValues> TaskFieldComboBoxValues { get; set; } = new List<TaskFieldComboBoxValues>();

    public virtual ICollection<TaskFieldData> TaskFieldData { get; set; } = new List<TaskFieldData>();
}