// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class TaskLogUsedArticles
{
    public int Id { get; set; }

    public int? TaskLogId { get; set; }

    public int? ArtId { get; set; }

    public double? NrOfArt { get; set; }

    public byte[] TimeStamp { get; set; }

    public int? UnscheduledTaskId { get; set; }

    public virtual Articles Art { get; set; }

    public virtual TaskLogs TaskLog { get; set; }

    public virtual UnscheduledTasks UnscheduledTask { get; set; }
}