// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class TaskClasses
{
    public int Id { get; set; }

    public string Name { get; set; }

    public byte[] Image { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual ICollection<TaskFields> TaskFields { get; set; } = new List<TaskFields>();

    public virtual ICollection<Tasks> Tasks { get; set; } = new List<Tasks>();
}