// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class TaskIntervals
{
    public int Id { get; set; }

    public int TaskId { get; set; }

    public int TaskTypeId { get; set; }

    public int? Interval { get; set; }

    public int? IntervalTypeId { get; set; }

    public int? LastTaskLogId { get; set; }

    public int? RoleId { get; set; }

    public DateOnly? CreateDate { get; set; }

    public int? NrDaysAccomplishBeforeNextDate { get; set; }

    public byte[] TimeStamp { get; set; }

    public int? AssignedToUserId { get; set; }

    public bool? Priority { get; set; }

    public double? NrDaysOrHoursPostponed { get; set; }

    public double? PreviousNrDaysOrHoursPostponed { get; set; }

    public int? VoninId { get; set; }

    public virtual Employees AssignedToUser { get; set; }

    public virtual IntervalTypes IntervalType { get; set; }

    public virtual ICollection<MonthDays> MonthDays { get; set; } = new List<MonthDays>();

    public virtual Roles Role { get; set; }

    public virtual Tasks Task { get; set; }

    public virtual ICollection<TaskIntervalsDates> TaskIntervalsDates { get; set; } = new List<TaskIntervalsDates>();

    public virtual ICollection<TaskIntervalsStoppedRestarted> TaskIntervalsStoppedRestarted { get; set; } = new List<TaskIntervalsStoppedRestarted>();

    public virtual TaskTypes TaskType { get; set; }

    public virtual ICollection<WeekDaysOrMonths> WeekDaysOrMonths { get; set; } = new List<WeekDaysOrMonths>();
}