// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class TaskTypes
{
    public int Id { get; set; }

    public string ShortName { get; set; }

    public string Name { get; set; }

    public int? Weight { get; set; }

    public byte[] TimeStamp { get; set; }

    public int? Color { get; set; }

    public string Comments { get; set; }

    public int? VoninId { get; set; }

    public virtual ICollection<TaskIntervals> TaskIntervals { get; set; } = new List<TaskIntervals>();

    public virtual ICollection<TaskLogs> TaskLogs { get; set; } = new List<TaskLogs>();

    public virtual ICollection<UnscheduledTasks> UnscheduledTasks { get; set; } = new List<UnscheduledTasks>();
}