// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class TaskLogs
{
    public int Id { get; set; }

    public int TaskId { get; set; }

    public int? TaskIntervalsId { get; set; }

    public DateTime? CompletedTime { get; set; }

    public int? UserId { get; set; }

    public int? TaskLogsListId { get; set; }

    public int? TaskTypeId { get; set; }

    public double? RunningHours { get; set; }

    public string Remark { get; set; }

    public int? ManHours { get; set; }

    public bool? FirstTaskLog { get; set; }

    public bool? Automatic { get; set; }

    public DateTime? NextDate { get; set; }

    public DateTime? UserCompletedTime { get; set; }

    public string Field1 { get; set; }

    public string Field2 { get; set; }

    public string Field3 { get; set; }

    public string Field4 { get; set; }

    public byte[] TimeStamp { get; set; }

    public DateTime? AddedDate { get; set; }

    public bool? Priority { get; set; }

    public string Field5 { get; set; }

    public string Field6 { get; set; }

    public string Field7 { get; set; }

    public string PostponeRemark { get; set; }

    public int? VoninId { get; set; }

    public virtual ICollection<AccomplishData> AccomplishData { get; set; } = new List<AccomplishData>();

    public virtual ICollection<Purchases> Purchases { get; set; } = new List<Purchases>();

    public virtual ICollection<TaskFieldData> TaskFieldData { get; set; } = new List<TaskFieldData>();

    public virtual ICollection<TaskLogDocuments> TaskLogDocuments { get; set; } = new List<TaskLogDocuments>();

    public virtual ICollection<TaskLogRemarks> TaskLogRemarks { get; set; } = new List<TaskLogRemarks>();

    public virtual ICollection<TaskLogUsedArticles> TaskLogUsedArticles { get; set; } = new List<TaskLogUsedArticles>();

    public virtual TaskLogsList TaskLogsList { get; set; }

    public virtual TaskTypes TaskType { get; set; }

    public virtual Employees User { get; set; }
}