// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class TaskLogsList
{
    public int Id { get; set; }

    public DateTime? CreatedTime { get; set; }

    public DateTime? CompletedTime { get; set; }

    public bool? Completed { get; set; }

    public bool? UseTemplate { get; set; }

    public int? UserId { get; set; }

    public int? StationId { get; set; }

    public int? RoleId { get; set; }

    public DateTime? TasksToDate { get; set; }

    public int? ComponentId { get; set; }

    public bool? Automatic { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual Roles Role { get; set; }

    public virtual ICollection<TaskLogs> TaskLogs { get; set; } = new List<TaskLogs>();

    public virtual Employees User { get; set; }
}