// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class TaskNameAndDescriptionHistory
{
    public int Id { get; set; }

    public int? TaskId { get; set; }

    public string TaskName { get; set; }

    public string TaskDescription { get; set; }

    public DateTime? ChangingDate { get; set; }

    public byte[] TimeStamp { get; set; }
}