// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class Tasks
{
    public int Id { get; set; }

    public int? ComponentId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int? LastTaskLogId { get; set; }

    public bool? StopRequired { get; set; }

    public bool? Automatic { get; set; }

    public int? ManHours { get; set; }

    public int? CreateUserId { get; set; }

    public DateTime? CreateDate { get; set; }

    public bool? Inactive { get; set; }

    public int? TaskClassId { get; set; }

    public byte[] TimeStamp { get; set; }

    public int? VoninId { get; set; }

    public bool? Stopped { get; set; }

    public virtual Components Component { get; set; }

    public virtual Employees CreateUser { get; set; }

    public virtual TaskClasses TaskClass { get; set; }

    public virtual ICollection<TaskDefaultArticles> TaskDefaultArticles { get; set; } = new List<TaskDefaultArticles>();

    public virtual ICollection<TaskIntervals> TaskIntervals { get; set; } = new List<TaskIntervals>();
}