// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class TaskFieldData
{
    public int Id { get; set; }

    public int? TaskLogId { get; set; }

    public int? TaskFieldId { get; set; }

    public string FieldData { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual TaskFields TaskField { get; set; }

    public virtual TaskLogs TaskLog { get; set; }
}