// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class TempComponentHoursAll
{
    public int CompId { get; set; }

    public double? CompHours { get; set; }

    public double? HoursNow { get; set; }
}