// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class Tempftasks
{
    public int? TaskId { get; set; }

    public int? TaskIntId { get; set; }

    public int? TaskTypeId { get; set; }

    public double? LeftTime { get; set; }

    public string LeftTimeChar { get; set; }

    public DateTime? NextDate { get; set; }

    public int? IntervalTypeId { get; set; }

    public string IntervalChar { get; set; }
}