// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class Tempintervals
{
    public int? EmployeeId { get; set; }

    public int? TaskIntervalsId { get; set; }

    public int? TaskId { get; set; }

    public int? ComponentId { get; set; }

    public int? TaskTypeId { get; set; }

    public int? RoleId { get; set; }

    public double? RunningHours { get; set; }

    public DateTime? LastLogDate { get; set; }

    public DateTime? NextLogDate { get; set; }

    public double? LeftTime { get; set; }

    public string LeftTimeChar { get; set; }

    public string IntervalChar { get; set; }
}