// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class tvf_ComponentMoveCopyLogs_DebugResult
    {
        public int? Reference { get; set; }
        public int ID { get; set; }
        public int? ComponentID { get; set; }
        public int Debug_UsesParents { get; set; }
        [StringLength(15)]
        public string Debug_TreeType { get; set; }
        public int? FromFolderID { get; set; }
        public int? ToFolderID { get; set; }
        public int? Debug_FromParentCount { get; set; }
        public int? Debug_ToParentCount { get; set; }
        [StringLength(500)]
        public string Debug_FirstFromParentName { get; set; }
        [StringLength(500)]
        public string Debug_FirstToParentName { get; set; }
        [StringLength(5000)]
        public string Debug_FromFolderTree { get; set; }
        [StringLength(5000)]
        public string Debug_ToFolderTree { get; set; }
        public string FromFolderName { get; set; }
        public string ToFolderName { get; set; }
    }
}
