// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class UnscheduledTaskDependence
{
    public int Id { get; set; }

    public int? UnscheduledTaskId { get; set; }

    public int? DependentUnscheduledTaskId { get; set; }

    public bool? Depends { get; set; }

    public int? FileId { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual UnscheduledTasks DependentUnscheduledTask { get; set; }

    public virtual FilesTable File { get; set; }
}