// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class UnscheduledTaskNeededArticles
{
    public int Id { get; set; }

    public int? UnscheduledTaskId { get; set; }

    public int? ArtId { get; set; }

    public int? ShelveId { get; set; }

    public double? Quantity { get; set; }

    public byte[] TimeStamp { get; set; }

    public double? OnStockQuantity { get; set; }

    public double? ArtCostPrice { get; set; }

    public int? OrdersArticleId { get; set; }

    public virtual Articles Art { get; set; }

    public virtual OrdersArticles OrdersArticle { get; set; }

    public virtual Shelves Shelve { get; set; }

    public virtual UnscheduledTasks UnscheduledTask { get; set; }
}