// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class UnscheduledTasks
{
    public int Id { get; set; }

    public int? NotificationId { get; set; }

    public string Description { get; set; }

    public DateTime? Date { get; set; }

    public int? UserId { get; set; }

    public string Title { get; set; }

    public int? Nr { get; set; }

    public int? CreatedRoleId { get; set; }

    public int? ResponsibleRoleId { get; set; }

    public int? ComponentId { get; set; }

    public bool Priority { get; set; }

    public bool Completed { get; set; }

    public DateTime? CompletedTime { get; set; }

    public bool? OnHold { get; set; }

    public DateTime? Deadline { get; set; }

    public int? CompletedUserId { get; set; }

    public string Action { get; set; }

    public int? FileId { get; set; }

    public int? Position { get; set; }

    public byte[] TimeStamp { get; set; }

    public double? ComponentHours { get; set; }

    public int? AssignedToUserId { get; set; }

    public int? TaskTypeId { get; set; }

    public double? Hours { get; set; }

    public string SiteLocation { get; set; }

    public bool? Warranty { get; set; }

    public int? VoninId { get; set; }

    public int? HdfId { get; set; }

    public double? NrDaysOrHoursPostponed { get; set; }

    public double? PreviousNrDaysOrHoursPostponed { get; set; }

    public string PostponeRemark { get; set; }

    public virtual Employees AssignedToUser { get; set; }

    public virtual Employees CompletedUser { get; set; }

    public virtual Components Component { get; set; }

    public virtual Roles CreatedRole { get; set; }

    public virtual FilesTable File { get; set; }

    public virtual Notifications Notification { get; set; }

    public virtual ICollection<OrdersUnscheduledTasks> OrdersUnscheduledTasks { get; set; } = new List<OrdersUnscheduledTasks>();

    public virtual ICollection<Purchases> Purchases { get; set; } = new List<Purchases>();

    public virtual Roles ResponsibleRole { get; set; }

    public virtual ICollection<TaskLogUsedArticles> TaskLogUsedArticles { get; set; } = new List<TaskLogUsedArticles>();

    public virtual TaskTypes TaskType { get; set; }

    public virtual ICollection<UnscheduledTaskDependence> UnscheduledTaskDependence { get; set; } = new List<UnscheduledTaskDependence>();

    public virtual ICollection<UnscheduledTaskDocuments> UnscheduledTaskDocuments { get; set; } = new List<UnscheduledTaskDocuments>();

    public virtual ICollection<UnscheduledTaskNeededArticles> UnscheduledTaskNeededArticles { get; set; } = new List<UnscheduledTaskNeededArticles>();

    public virtual ICollection<UnscheduledTaskRemarks> UnscheduledTaskRemarks { get; set; } = new List<UnscheduledTaskRemarks>();

    public virtual Employees User { get; set; }
}