// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class UnscheduledTasksSendEmailOptions
{
    public int Id { get; set; }

    public string Option { get; set; }

    public virtual ICollection<Company> Company { get; set; } = new List<Company>();
}