// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class UnscheduledTaskRemarks
{
    public int Id { get; set; }

    public int? UnscheduledTaskId { get; set; }

    public string Remark { get; set; }

    public int? UserId { get; set; }

    public DateTime? Date { get; set; }

    public byte[] TimeStamp { get; set; }

    public virtual UnscheduledTasks UnscheduledTask { get; set; }

    public virtual Employees User { get; set; }
}