// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class Users
{
    public int UserId { get; set; }

    public string UserName { get; set; }

    public string UserPswd { get; set; }

    public int? ViewTodoId { get; set; }

    public bool? IsAdmin { get; set; }

    public int? DriverNr { get; set; }

    public bool? IsWarehouseUser { get; set; }

    public bool? IsInactive { get; set; }

    public DateTime? LastActivityAt { get; set; }

    public string LastActivityIn { get; set; }

    public int? UserRoleId { get; set; }

    public byte[] PhotoImage { get; set; }

    public string LoginName { get; set; }

    public string Email { get; set; }

    public string FullName { get; set; }
}