// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class UserApplicationViewFavourite
{
    public int UserApplicationViewFavouriteId { get; set; }

    public int? UserId { get; set; }

    public int? ApplicationViewId { get; set; }

    public int? Relatedid { get; set; }

    public DateTime? AddedTime { get; set; }

    public string ViewTitle { get; set; }

    public byte[] Concurency { get; set; }

    public string Staffcode { get; set; }
}