// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class usp_app_util_changelog_sync_triggersResult
    {
        [StringLength(128)]
        public string TableName { get; set; }
        [StringLength(128)]
        public string TriggerName { get; set; }
        public string ActionType { get; set; }
        public bool? Executed { get; set; }
        [StringLength(2147483647)]
        public string SqlText { get; set; }
    }
}
