// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class usp_util_loginResult
    {
        public int? NewSessionId { get; set; }
        public bool IsVersionFirstTimeOpened { get; set; }
    }
}
