// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class usp_app_util_refresh_statusResult
    {
        [StringLength(50)]
        public string TableName { get; set; }
        public DateTime? ServerTime { get; set; }
    }
}
