// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class usp_app_Users_UserInfo12Result
    {
        public int UserId { get; set; }
        [StringLength(10)]
        public string LoginName { get; set; }
        [StringLength(50)]
        public string UserName { get; set; }
        [StringLength(300)]
        public string Email { get; set; }
        public bool? IsInactive { get; set; }
        public byte[] PhotoImage { get; set; }
        public int? UserRoleId { get; set; }
        [StringLength(32)]
        public string RoleName { get; set; }
        [StringLength(50)]
        public string UserPswd { get; set; }
        [StringLength(250)]
        public string FullName { get; set; }
    }
}
