// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class usp_app_util_log_get_changesResult
    {
        public int ChangeLogSessionId { get; set; }
        public int ChangeLogId { get; set; }
        public DateTime? ChangeTime { get; set; }
        public DateTime? LoggedTime { get; set; }
        public int? UserId { get; set; }
        [StringLength(50)]
        public string UserName { get; set; }
        [StringLength(250)]
        public string TableName { get; set; }
        [StringLength(250)]
        public string TableFriendlyName { get; set; }
        [StringLength(2147483647)]
        public string PKValue { get; set; }
        public string ActionType { get; set; }
        [StringLength(250)]
        public string ColumnName { get; set; }
        [StringLength(250)]
        public string ColumnDescription { get; set; }
        [StringLength(2147483647)]
        public string OldValue { get; set; }
        [StringLength(2147483647)]
        public string NewValue { get; set; }
        public bool HasChange { get; set; }
        public int? SortPriority { get; set; }
        [StringLength(70)]
        public string ColumnForGrouping { get; set; }
        [StringLength(2147483647)]
        public string ColumnForGrouping2 { get; set; }
    }
}
