// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class usp_app_lookup_UserRoleInfoResult
    {
        public int UserRoleId { get; set; }
        [StringLength(32)]
        public string RoleName { get; set; }
    }
}
