// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class usp_app_Users_UserInfoResult
    {
        public int UserID { get; set; }
        [StringLength(50)]
        public string ShortName { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
    }
}
