// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Opus.Mobile.Data.Models
{
    public partial class usp_app_startup_ApplicationViewInfo_LoadResult
    {
        public int ApplicationViewId { get; set; }
        [StringLength(100)]
        public string ViewName { get; set; }
        public bool? IsMainView { get; set; }
        public bool? IsDialog { get; set; }
        public int ModuleId { get; set; }
        [StringLength(100)]
        public string ModuleName { get; set; }
        public int AllowRead { get; set; }
        public int AllowSave { get; set; }
        public int IsAdmin { get; set; }
        [StringLength(6)]
        public string ViewMainDBTableName { get; set; }
        public int SortProperty { get; set; }
    }
}
