// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class UtilChangeLogSession
{
    public int ChangeLogSessionId { get; set; }

    public DateTime? LoggedTime { get; set; }

    public int? UserId { get; set; }

    public int? ApplicationViewId { get; set; }

    public string TableName { get; set; }

    public string Pkvalue { get; set; }

    public Guid ApplicationGuid { get; set; }

    public virtual ApplicationView ApplicationView { get; set; }

    public virtual ICollection<UtilChangeLog> UtilChangeLog { get; set; } = new List<UtilChangeLog>();

    public virtual ICollection<UtilChangeLogCurrent> UtilChangeLogCurrent { get; set; } = new List<UtilChangeLogCurrent>();
}