// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class UtilChangeLogColumn
{
    public int ChangeLogColumnId { get; set; }

    public int ChangeLogId { get; set; }

    public string ColumnName { get; set; }

    public string OldValue { get; set; }

    public string NewValue { get; set; }

    public bool HasChange { get; set; }

    public string OldFkValue { get; set; }

    public string NewFkValue { get; set; }

    public virtual UtilChangeLog ChangeLog { get; set; }
}