// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class UtilRefreshStatus
{
    public string TableName { get; set; }

    public DateTime? LastChange { get; set; }
}