// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class UtilLogin
{
    public int UtilLoginId { get; set; }

    public string AppName { get; set; }

    public int? LoggedInUserId { get; set; }

    public string AppDescription { get; set; }
}