// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class UtilChangeLogCurrent
{
    public string AppName { get; set; }

    public Guid ApplicationGuid { get; set; }

    public virtual UtilChangeLogSession Application { get; set; }
}