// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class UtilChangeLog
{
    public int ChangeLogId { get; set; }

    public int? ChangeLogSessionId { get; set; }

    public int? UserId { get; set; }

    public DateTime? ChangeTime { get; set; }

    public string TableName { get; set; }

    public string Pkvalue { get; set; }

    public string ActionType { get; set; }

    public string Deleted { get; set; }

    public string Inserted { get; set; }

    public bool IsProcessed { get; set; }

    public virtual UtilChangeLogSession ChangeLogSession { get; set; }

    public virtual ICollection<UtilChangeLogColumn> UtilChangeLogColumn { get; set; } = new List<UtilChangeLogColumn>();
}