// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class Vcomponents
{
    public string Sfiname1 { get; set; }

    public int Id { get; set; }

    public string Name1 { get; set; }

    public string Name2 { get; set; }

    public int? CounterId { get; set; }

    public string SerialNr { get; set; }

    public string TypeNr { get; set; }

    public int? ParentId { get; set; }

    public int? ClassId { get; set; }

    public string TagNr { get; set; }

    public int? Position { get; set; }

    public int? GroupArtId { get; set; }

    public bool? IsComponent { get; set; }

    public bool? Inactive { get; set; }

    public string Description { get; set; }

    public int? ArtId { get; set; }

    public bool? Critical { get; set; }

    public string Sfi2 { get; set; }

    public int? ManufacturerId { get; set; }

    public int? RefComponentId { get; set; }

    public byte[] TimeStamp { get; set; }

    public string Location1 { get; set; }

    public int? VoninId { get; set; }

    public double? MonthlyRentPrice { get; set; }

    public byte[] Image { get; set; }

    public int? VoninParentId { get; set; }

    public DateTime? Date { get; set; }

    public int? SupplierId { get; set; }

    public string Specification { get; set; }

    public byte[] ImageThumbnail { get; set; }
}