// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class VcomponentsTree
{
    public int Id { get; set; }

    public int? CounterId { get; set; }

    public double Hours { get; set; }

    public bool? Inactive { get; set; }

    public string Sfi { get; set; }

    public string ComponentTree { get; set; }
}