// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class VcomponentsSelectGroupArtIdandCount
{
    public int? GroupArtId { get; set; }

    public int? Cnt { get; set; }
}