// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class Vdocuments
{
    public int Id { get; set; }

    public byte[] Doc { get; set; }

    public string Description { get; set; }

    public string Extension { get; set; }

    public double? DocSize { get; set; }

    public int? CreateUserId { get; set; }

    public DateTime? CreateDate { get; set; }

    public byte[] Thumbnail { get; set; }

    public byte[] SmallJpg { get; set; }
}