// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class VgetStockHavsbrun
{
    public string Nr { get; set; }

    public string Description { get; set; }

    public double? Quantity { get; set; }

    public double? CostPrice { get; set; }

    public string StockName { get; set; }
}