// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class Vnotifications
{
    public int Id { get; set; }

    public string Description { get; set; }

    public DateTime? Date { get; set; }

    public int? UserId { get; set; }

    public string Title { get; set; }

    public int? Nr { get; set; }

    public int? CreatedRoleId { get; set; }

    public int? ResponsibleRoleId { get; set; }

    public int? NotificationTypeId { get; set; }

    public int? ComponentId { get; set; }

    public bool? Priority { get; set; }

    public bool? Completed { get; set; }

    public string Remark { get; set; }

    public DateTime? CompletedTime { get; set; }

    public int? CompletedUserId { get; set; }

    public string CreatedRole { get; set; }

    public string ResponsibleRole { get; set; }

    public string CreatedBy { get; set; }

    public string AccomplishedBy { get; set; }

    public string Type { get; set; }

    public string Component { get; set; }
}