// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class VordersReceivedArticles
{
    public int? OrderId { get; set; }

    public int? Artid { get; set; }

    public string ArtNr { get; set; }

    public string ArtDescription { get; set; }

    public string ArtUnit { get; set; }

    public double? Quantity { get; set; }
}