// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class Vorders
{
    public int Id { get; set; }

    public int? OrderNr { get; set; }

    public string Description { get; set; }

    public int? SupplId { get; set; }

    public string SupplName { get; set; }

    public string SupplAdress1 { get; set; }

    public string SupplAdress2 { get; set; }

    public string SupplAdress3 { get; set; }

    public string SupplAdress4 { get; set; }

    public int? SupplCityId { get; set; }

    public int? SupplCountryId { get; set; }

    public string SupplPhone { get; set; }

    public string SupplFax { get; set; }

    public string SupplEmail { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? CompleteDate { get; set; }

    public DateTime? DeliveryDate { get; set; }

    public bool? OrderedByPhone { get; set; }

    public string DepartId { get; set; }

    public int? AccountId { get; set; }

    public int? OurPersonId { get; set; }

    public int? SupplPersonId { get; set; }

    public int? CreateUserId { get; set; }

    public double? Value { get; set; }

    public int? CurrencyId { get; set; }

    public bool? Printed { get; set; }

    public DateTime? Regtime { get; set; }

    public bool? Closed { get; set; }

    public int? CompanyDeliveryAddressId { get; set; }

    public bool? Deleted { get; set; }

    public bool? Sent { get; set; }

    public byte[] TimeStamp { get; set; }

    public string Remarks { get; set; }

    public string DeliveryTerms { get; set; }

    public string TransportMode { get; set; }

    public double? NrOfColli { get; set; }

    public double? TotalWeight { get; set; }

    public int? ShipperId { get; set; }

    public int? ShipperPersonId { get; set; }

    public int? ComponentId { get; set; }

    public DateOnly? Deadline { get; set; }

    public string SupplPostalCode { get; set; }

    public string Remark { get; set; }

    public byte[] Image { get; set; }
}