// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class VPowerbiCurrentStock
{
    public int ArtId { get; set; }

    public double QuantiyyOnStock { get; set; }

    public string ArticleNr { get; set; }

    public string ArticleDecription { get; set; }
}