// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class VPowerbiComponents
{
    public int ComponentId { get; set; }

    public string Name1 { get; set; }

    public string Name2 { get; set; }

    public string Description { get; set; }

    public string SerialNr { get; set; }

    public string TagNr { get; set; }

    public string TypeNr { get; set; }

    public string ComponentClass { get; set; }

    public string Parent1Name { get; set; }

    public string Parent2Name { get; set; }

    public string Parent3Name { get; set; }

    public string Room { get; set; }
}