// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class VPowerbiTaskTimeline
{
    public string TaskId { get; set; }

    public DateTime Date { get; set; }
}