// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class VPowerbiComponentRoot
{
    public int ComponentId { get; set; }

    public string RootName { get; set; }
}