// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class VPowerbiSuppliers
{
    public int SupplId { get; set; }

    public string SupplierName { get; set; }

    public string CountryName { get; set; }

    public int? Account { get; set; }

    public string Adress1 { get; set; }

    public string Adress2 { get; set; }

    public string Adress3 { get; set; }

    public string Adress4 { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string PostalCode { get; set; }

    public string WebSite { get; set; }

    public string Status { get; set; }
}