// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class VPowerbiUsedArticles
{
    public string TaskId { get; set; }

    public int? ArtId { get; set; }

    public double? ArtCostPrice { get; set; }

    public DateOnly? Date { get; set; }

    public double? Quantity { get; set; }

    public string ArticleNr { get; set; }

    public string ArticleDecription { get; set; }

    public string EmployeeShortName { get; set; }

    public string EmployeeFullName { get; set; }

    public string EmployeeRole { get; set; }
}