// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class VPowerbiReceivedArticles
{
    public int OrderId { get; set; }

    public int? ArtId { get; set; }

    public double? Quantity { get; set; }

    public string OrderArticleDescription { get; set; }

    public DateOnly? ReceivedDate { get; set; }

    public string ArticleNr { get; set; }

    public string ArticleDecription { get; set; }

    public double? CostPrice { get; set; }
}