// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class VPowerbiOrders
{
    public int OrderId { get; set; }

    public int? OrderNr { get; set; }

    public string Description { get; set; }

    public DateOnly? Deadline { get; set; }

    public string Status { get; set; }

    public int? SupplId { get; set; }

    public string AccountName { get; set; }

    public string DeliveryTo { get; set; }

    public string Remark { get; set; }

    public int? ComponentId { get; set; }

    public string CreatedShortName { get; set; }

    public DateOnly? CreatedDate { get; set; }
}