// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class VPowerbiFiles
{
    public int? FileNr { get; set; }

    public string FileTitle { get; set; }

    public string FileDescription { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ClosedDate { get; set; }
}