// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class VPowerbiOrderItems
{
    public int OrderId { get; set; }

    public int? ArtId { get; set; }

    public string ArticleDescription { get; set; }

    public double? OrderedQuantity { get; set; }

    public double? Discount { get; set; }

    public double? OrderPrice { get; set; }
}