// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class VshelvesRacksStocks
{
    public int ShelveId { get; set; }

    public int RackId { get; set; }

    public int StockId { get; set; }

    public string ShelveName { get; set; }

    public string RackName { get; set; }

    public string StockName { get; set; }

    public string StockLongName { get; set; }
}