// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class VsuppliersInvoices
{
    public int Id { get; set; }

    public int? OrderId { get; set; }

    public string Nr { get; set; }

    public DateTime? Date { get; set; }

    public double? Value { get; set; }

    public bool? Closed { get; set; }

    public string Note { get; set; }

    public int? SupplierId { get; set; }

    public int? AccountId { get; set; }

    public int? LastInvoiceEventId { get; set; }

    public string SupplierNotDb { get; set; }

    public int? FileId { get; set; }

    public bool? Deleted { get; set; }

    public byte[] TimeStamp { get; set; }
}