// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class VtaskLogs
{
    public int Id { get; set; }

    public int TaskId { get; set; }

    public int? TaskIntervalsId { get; set; }

    public DateTime? CompletedTime { get; set; }

    public int? UserId { get; set; }

    public int? TaskLogsListId { get; set; }

    public int? TaskTypeId { get; set; }

    public double? RunningHours { get; set; }

    public string Remark { get; set; }

    public int? ManHours { get; set; }

    public bool? FirstTaskLog { get; set; }

    public bool? Automatic { get; set; }

    public DateTime? NextDate { get; set; }

    public DateTime? UserCompletedTime { get; set; }

    public string Field1 { get; set; }

    public string Field2 { get; set; }

    public string Field3 { get; set; }

    public string Field4 { get; set; }

    public byte[] TimeStamp { get; set; }

    public DateTime? AddedDate { get; set; }

    public bool? Priority { get; set; }

    public string Field5 { get; set; }

    public string Field6 { get; set; }

    public string Field7 { get; set; }

    public int? ComponentId { get; set; }
}