// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class VtaskIntervals
{
    public int Id { get; set; }

    public int TaskId { get; set; }

    public int TaskTypeId { get; set; }

    public int? Interval { get; set; }

    public int? IntervalTypeId { get; set; }

    public int? LastTaskLogId { get; set; }

    public int? RoleId { get; set; }

    public DateOnly? CreateDate { get; set; }

    public int? NrDaysAccomplishBeforeNextDate { get; set; }

    public byte[] TimeStamp { get; set; }

    public int? AssignedToUserId { get; set; }

    public bool? Priority { get; set; }

    public int? ComponentId { get; set; }
}