// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Opus.Mobile.Data.Models;

public partial class XamaLogin
{
    public int XamaLoginId { get; set; }

    public int? UserId { get; set; }

    public string Token { get; set; }
}