// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Opus.Mobile.Data.Models;

namespace Opus.Mobile.Data.Context
{
    public partial class OpusDBContext
    {

        [DbFunction("CalculateTotal", "dbo")]
        public static decimal? CalculateTotal(decimal? price, int? quantity, decimal? discount)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("CalculateTotalWithDefaults", "dbo")]
        public static decimal? CalculateTotalWithDefaults(decimal? price, int? quantity, decimal? discount)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("FAccesLevelEmployees", "dbo")]
        public static string FAccesLevelEmployees(int? p_compID, int? P_empID)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("FAccesLevelRoles", "dbo")]
        public static string FAccesLevelRoles(int? p_compID, int? p_roleID)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("FAccessRights", "dbo")]
        public IQueryable<FAccessRightsResult> FAccessRights(int? p_EmployeeID)
        {
            return FromExpression(() => FAccessRights(p_EmployeeID));
        }

        [DbFunction("FAliringarComponents", "dbo")]
        public IQueryable<FAliringarComponentsResult> FAliringarComponents()
        {
            return FromExpression(() => FAliringarComponents());
        }

        [DbFunction("FArticles", "dbo")]
        public IQueryable<FArticlesResult> FArticles()
        {
            return FromExpression(() => FArticles());
        }

        [DbFunction("FArticles_UnitsOfMeasure_ArticlesSuppliers", "dbo")]
        public IQueryable<FArticles_UnitsOfMeasure_ArticlesSuppliersResult> FArticles_UnitsOfMeasure_ArticlesSuppliers(int? p_SupplierID)
        {
            return FromExpression(() => FArticles_UnitsOfMeasure_ArticlesSuppliers(p_SupplierID));
        }

        [DbFunction("FArticlesBelowMinimumStock", "dbo")]
        public IQueryable<FArticlesBelowMinimumStockResult> FArticlesBelowMinimumStock()
        {
            return FromExpression(() => FArticlesBelowMinimumStock());
        }

        [DbFunction("FArticlesDefaultStocks", "dbo")]
        public IQueryable<FArticlesDefaultStocksResult> FArticlesDefaultStocks(int? p_artID)
        {
            return FromExpression(() => FArticlesDefaultStocks(p_artID));
        }

        [DbFunction("FArticlesOpenedOrders", "dbo")]
        public IQueryable<FArticlesOpenedOrdersResult> FArticlesOpenedOrders(int? p_artID)
        {
            return FromExpression(() => FArticlesOpenedOrders(p_artID));
        }

        [DbFunction("FComponentAllParents", "dbo")]
        public IQueryable<FComponentAllParentsResult> FComponentAllParents(int? CompId, bool? WalkByReference)
        {
            return FromExpression(() => FComponentAllParents(CompId, WalkByReference));
        }

        [DbFunction("FComponentClasses", "dbo")]
        public IQueryable<FComponentClassesResult> FComponentClasses()
        {
            return FromExpression(() => FComponentClasses());
        }

        [DbFunction("FComponentDataFields", "dbo")]
        public IQueryable<FComponentDataFieldsResult> FComponentDataFields()
        {
            return FromExpression(() => FComponentDataFields());
        }

        [DbFunction("FComponentDoesntHaveCounters", "dbo")]
        public static bool? FComponentDoesntHaveCounters(int? p_compID)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("FComponentHours", "dbo")]
        public IQueryable<FComponentHoursResult> FComponentHours(int? P_COMPID)
        {
            return FromExpression(() => FComponentHours(P_COMPID));
        }

        [DbFunction("FComponentHoursAll", "dbo")]
        public IQueryable<FComponentHoursAllResult> FComponentHoursAll()
        {
            return FromExpression(() => FComponentHoursAll());
        }

        [DbFunction("FComponentHoursAllV2", "dbo")]
        public IQueryable<FComponentHoursAllV2Result> FComponentHoursAllV2()
        {
            return FromExpression(() => FComponentHoursAllV2());
        }

        [DbFunction("FComponentHoursDifference", "dbo")]
        public static int? FComponentHoursDifference(int? p_compID, DateTime? p_DT1, DateTime? p_DT2)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("FComponentList", "dbo")]
        public IQueryable<FComponentListResult> FComponentList()
        {
            return FromExpression(() => FComponentList());
        }

        [DbFunction("FComponentMoveCopyLogs", "dbo")]
        public IQueryable<FComponentMoveCopyLogsResult> FComponentMoveCopyLogs(long? ComponentID)
        {
            return FromExpression(() => FComponentMoveCopyLogs(ComponentID));
        }

        [DbFunction("FComponents", "dbo")]
        public IQueryable<FComponentsResult> FComponents()
        {
            return FromExpression(() => FComponents());
        }

        [DbFunction("FComponentsAllReferences", "dbo")]
        public static string FComponentsAllReferences(int? p_ID)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("FComponentTree", "dbo")]
        public IQueryable<FComponentTreeResult> FComponentTree()
        {
            return FromExpression(() => FComponentTree());
        }

        [DbFunction("FComponentTree_NEW", "dbo")]
        public IQueryable<FComponentTree_NEWResult> FComponentTree_NEW()
        {
            return FromExpression(() => FComponentTree_NEW());
        }

        [DbFunction("FCounters", "dbo")]
        public IQueryable<FCountersResult> FCounters()
        {
            return FromExpression(() => FCounters());
        }

        [DbFunction("FDateOnly", "dbo")]
        public static DateTime? FDateOnly(DateTime? p)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("FDayName", "dbo")]
        public static string FDayName(int? p_day)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("FEmployees", "dbo")]
        public IQueryable<FEmployeesResult> FEmployees()
        {
            return FromExpression(() => FEmployees());
        }

        [DbFunction("FEmployeesByRoleID", "dbo")]
        public IQueryable<FEmployeesByRoleIDResult> FEmployeesByRoleID(int? p_RoleID)
        {
            return FromExpression(() => FEmployeesByRoleID(p_RoleID));
        }

        [DbFunction("FEmpty", "dbo")]
        public static string FEmpty(string p)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("FExchangeRate", "dbo")]
        public static double? FExchangeRate(int? p_CurrencyID)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("FFilesArticles", "dbo")]
        public IQueryable<FFilesArticlesResult> FFilesArticles()
        {
            return FromExpression(() => FFilesArticles());
        }

        [DbFunction("FFirstDateOfMonth", "dbo")]
        public static DateTime? FFirstDateOfMonth(DateTime? p)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("FGetAllActiveTasks", "dbo")]
        public IQueryable<FGetAllActiveTasksResult> FGetAllActiveTasks()
        {
            return FromExpression(() => FGetAllActiveTasks());
        }

        [DbFunction("FGetAllRoles", "dbo")]
        public IQueryable<FGetAllRolesResult> FGetAllRoles()
        {
            return FromExpression(() => FGetAllRoles());
        }

        [DbFunction("FGetArticleStockInformation", "dbo")]
        public IQueryable<FGetArticleStockInformationResult> FGetArticleStockInformation(int? ArtID)
        {
            return FromExpression(() => FGetArticleStockInformation(ArtID));
        }

        [DbFunction("FGetArticleTaskComponentInterval", "dbo")]
        public IQueryable<FGetArticleTaskComponentIntervalResult> FGetArticleTaskComponentInterval(int? p_artID)
        {
            return FromExpression(() => FGetArticleTaskComponentInterval(p_artID));
        }

        [DbFunction("FGetNAPRoles", "dbo")]
        public IQueryable<FGetNAPRolesResult> FGetNAPRoles()
        {
            return FromExpression(() => FGetNAPRoles());
        }

        [DbFunction("FGetOperations", "dbo")]
        public IQueryable<FGetOperationsResult> FGetOperations(int? p_artID, DateTime? p_date1, DateTime? p_date2)
        {
            return FromExpression(() => FGetOperations(p_artID, p_date1, p_date2));
        }

        [DbFunction("FGetStock", "dbo")]
        public IQueryable<FGetStockResult> FGetStock(DateTime? p_date, int? p_artID, int? p_stockID, int? p_rackID, int? p_shelveID)
        {
            return FromExpression(() => FGetStock(p_date, p_artID, p_stockID, p_rackID, p_shelveID));
        }

        [DbFunction("FGetStock_NEW", "dbo")]
        public IQueryable<FGetStock_NEWResult> FGetStock_NEW(DateTime? p_date, int? p_artID, int? p_stockID, int? p_rackID, int? p_shelveID)
        {
            return FromExpression(() => FGetStock_NEW(p_date, p_artID, p_stockID, p_rackID, p_shelveID));
        }

        [DbFunction("FGetStockTotal", "dbo")]
        public IQueryable<FGetStockTotalResult> FGetStockTotal(DateTime? p_date, int? p_artID, int? p_stockID, int? p_rackID, int? p_shelveID)
        {
            return FromExpression(() => FGetStockTotal(p_date, p_artID, p_stockID, p_rackID, p_shelveID));
        }

        [DbFunction("FGetStockTotal_NEW", "dbo")]
        public IQueryable<FGetStockTotal_NEWResult> FGetStockTotal_NEW(DateTime? p_date, int? p_artID, int? p_stockID, int? p_rackID, int? p_shelveID)
        {
            return FromExpression(() => FGetStockTotal_NEW(p_date, p_artID, p_stockID, p_rackID, p_shelveID));
        }

        [DbFunction("FGetTaskLogs", "dbo")]
        public IQueryable<FGetTaskLogsResult> FGetTaskLogs(int? p_TaskID)
        {
            return FromExpression(() => FGetTaskLogs(p_TaskID));
        }

        [DbFunction("FGroupsOfArticles", "dbo")]
        public IQueryable<FGroupsOfArticlesResult> FGroupsOfArticles()
        {
            return FromExpression(() => FGroupsOfArticles());
        }

        [DbFunction("FHDFBranches", "dbo")]
        public IQueryable<FHDFBranchesResult> FHDFBranches()
        {
            return FromExpression(() => FHDFBranches());
        }

        [DbFunction("FInitials", "dbo")]
        public static string FInitials(string p_string, string p_split)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("FIntervals", "dbo")]
        public IQueryable<FIntervalsResult> FIntervals(int? p_taskID, int? p_compID)
        {
            return FromExpression(() => FIntervals(p_taskID, p_compID));
        }

        [DbFunction("FIntervalsChar", "dbo")]
        public static string FIntervalsChar(int? p_TaskIntervalsID, int? p_intervalTypeID)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("FIntervalsDueDate", "dbo")]
        public IQueryable<FIntervalsDueDateResult> FIntervalsDueDate(DateTime? p_dueDate)
        {
            return FromExpression(() => FIntervalsDueDate(p_dueDate));
        }

        [DbFunction("FIntervalsLowerWeight", "dbo")]
        public IQueryable<FIntervalsLowerWeightResult> FIntervalsLowerWeight(int? p_TaskIntervalID)
        {
            return FromExpression(() => FIntervalsLowerWeight(p_TaskIntervalID));
        }

        [DbFunction("FIsMTH", "dbo")]
        public static bool? FIsMTH()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        public async Task<bool?> FIsMTHAsync()
            => await Database.SqlQueryRaw<bool?>("select Value = [dbo].[FIsMTH]()").SingleAsync();

        [DbFunction("FLastCostPrice", "dbo")]
        public static double? FLastCostPrice(int? p_artID, DateTime? p_dt, int? p_shelveID)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("FLastTaskLogRow", "dbo")]
        public IQueryable<FLastTaskLogRowResult> FLastTaskLogRow(int? p_taskIntID)
        {
            return FromExpression(() => FLastTaskLogRow(p_taskIntID));
        }

        [DbFunction("FMaxDate", "dbo")]
        public static DateTime? FMaxDate(DateTime? p_dt1, DateTime? p_dt2)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("FMaxOrderInternalNr", "dbo")]
        public static int? FMaxOrderInternalNr(int? pIpoLpoID)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("FMonthName", "dbo")]
        public static string FMonthName(int? p_month)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("FOneComponentTree", "dbo")]
        public IQueryable<FOneComponentTreeResult> FOneComponentTree(int? p_compID)
        {
            return FromExpression(() => FOneComponentTree(p_compID));
        }

        [DbFunction("FOpenedOrdersQuantity", "dbo")]
        public IQueryable<FOpenedOrdersQuantityResult> FOpenedOrdersQuantity()
        {
            return FromExpression(() => FOpenedOrdersQuantity());
        }

        [DbFunction("FRacks", "dbo")]
        public IQueryable<FRacksResult> FRacks(int? p_stockID)
        {
            return FromExpression(() => FRacks(p_stockID));
        }

        [DbFunction("FRoleByID", "dbo")]
        public static string FRoleByID(int? pRoleID)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("FRptTaskSummary_AccomplishedTasks", "dbo")]
        public IQueryable<FRptTaskSummary_AccomplishedTasksResult> FRptTaskSummary_AccomplishedTasks(int? p_RootID)
        {
            return FromExpression(() => FRptTaskSummary_AccomplishedTasks(p_RootID));
        }

        [DbFunction("FRptTaskSummary_NextTasks", "dbo")]
        public IQueryable<FRptTaskSummary_NextTasksResult> FRptTaskSummary_NextTasks(int? p_RootID, int? P_NextNrDays)
        {
            return FromExpression(() => FRptTaskSummary_NextTasks(p_RootID, P_NextNrDays));
        }

        [DbFunction("FRptTaskSummary_Notifications", "dbo")]
        public IQueryable<FRptTaskSummary_NotificationsResult> FRptTaskSummary_Notifications(int? p_RootID, DateTime? p_FromDate, DateTime? p_ToDate)
        {
            return FromExpression(() => FRptTaskSummary_Notifications(p_RootID, p_FromDate, p_ToDate));
        }

        [DbFunction("FRptTaskSummary_UnscheduledTasks", "dbo")]
        public IQueryable<FRptTaskSummary_UnscheduledTasksResult> FRptTaskSummary_UnscheduledTasks(int? p_RootID, DateTime? p_FromDate, DateTime? p_ToDate)
        {
            return FromExpression(() => FRptTaskSummary_UnscheduledTasks(p_RootID, p_FromDate, p_ToDate));
        }

        [DbFunction("FSelectParameter", "dbo")]
        public static string FSelectParameter(bool? p_Select, string p1, string p2)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("FSelectScheduledUnscheduledTasks", "dbo")]
        public IQueryable<FSelectScheduledUnscheduledTasksResult> FSelectScheduledUnscheduledTasks(int? p_compID)
        {
            return FromExpression(() => FSelectScheduledUnscheduledTasks(p_compID));
        }

        [DbFunction("FSfi", "dbo")]
        public static string FSfi(int? p_compID)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("FShelves", "dbo")]
        public IQueryable<FShelvesResult> FShelves(int? RackID)
        {
            return FromExpression(() => FShelves(RackID));
        }

        [DbFunction("FSplitString", "dbo")]
        public static string FSplitString(string p_string, string p_split, bool? p_first)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("FSplitStringToTable", "dbo")]
        public IQueryable<FSplitStringToTableResult> FSplitStringToTable(string ItemList, string delimiter)
        {
            return FromExpression(() => FSplitStringToTable(ItemList, delimiter));
        }

        [DbFunction("FStocksBelowMinimum", "dbo")]
        public IQueryable<FStocksBelowMinimumResult> FStocksBelowMinimum()
        {
            return FromExpression(() => FStocksBelowMinimum());
        }

        [DbFunction("FStocksList", "dbo")]
        public IQueryable<FStocksListResult> FStocksList()
        {
            return FromExpression(() => FStocksList());
        }

        [DbFunction("FSubComponents", "dbo")]
        public IQueryable<FSubComponentsResult> FSubComponents(int? P_ID, bool? IncludeParameterComponent)
        {
            return FromExpression(() => FSubComponents(P_ID, IncludeParameterComponent));
        }

        [DbFunction("FSubComponents1", "dbo")]
        public IQueryable<FSubComponents1Result> FSubComponents1(int? p_ID)
        {
            return FromExpression(() => FSubComponents1(p_ID));
        }

        [DbFunction("FSubComponentsAndParameterComponent", "dbo")]
        public IQueryable<FSubComponentsAndParameterComponentResult> FSubComponentsAndParameterComponent(int? p_ID)
        {
            return FromExpression(() => FSubComponentsAndParameterComponent(p_ID));
        }

        [DbFunction("FSubComponentsCount", "dbo")]
        public static int? FSubComponentsCount(int? P_ID, bool? IncludeParameterComponent)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("FSuppliers", "dbo")]
        public IQueryable<FSuppliersResult> FSuppliers()
        {
            return FromExpression(() => FSuppliers());
        }

        [DbFunction("FSuppliersInvoiceEmailBody", "dbo")]
        public static string FSuppliersInvoiceEmailBody(int? pSuppliersInvoiceID)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("FSuppliersInvoicesStatus", "dbo")]
        public IQueryable<FSuppliersInvoicesStatusResult> FSuppliersInvoicesStatus()
        {
            return FromExpression(() => FSuppliersInvoicesStatus());
        }

        [DbFunction("FTableColumns", "dbo")]
        public static string FTableColumns(string pTable)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("FTableColumnsList", "dbo")]
        public static string FTableColumnsList(int? p_objectID)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("FTableFieldComboBoxValues", "dbo")]
        public IQueryable<FTableFieldComboBoxValuesResult> FTableFieldComboBoxValues(int? p_TableFieldID)
        {
            return FromExpression(() => FTableFieldComboBoxValues(p_TableFieldID));
        }

        [DbFunction("FTaskClasses", "dbo")]
        public IQueryable<FTaskClassesResult> FTaskClasses()
        {
            return FromExpression(() => FTaskClasses());
        }

        [DbFunction("FTaskFieldData", "dbo")]
        public IQueryable<FTaskFieldDataResult> FTaskFieldData(int? pTaskLogID)
        {
            return FromExpression(() => FTaskFieldData(pTaskLogID));
        }

        [DbFunction("FTaskLogAccomplish", "dbo")]
        public static int? FTaskLogAccomplish(int? p_TaskLogID)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("FTasks", "dbo")]
        public IQueryable<FTasksResult> FTasks(int? P_componentID)
        {
            return FromExpression(() => FTasks(P_componentID));
        }

        [DbFunction("FTasksStatus", "dbo")]
        public IQueryable<FTasksStatusResult> FTasksStatus()
        {
            return FromExpression(() => FTasksStatus());
        }

        [DbFunction("FTaskTypes", "dbo")]
        public IQueryable<FTaskTypesResult> FTaskTypes()
        {
            return FromExpression(() => FTaskTypes());
        }

        [DbFunction("fu_app_changelog_session_id", "dbo")]
        public static int? fu_app_changelog_session_id()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        public async Task<int?> fu_app_changelog_session_idAsync()
            => await Database.SqlQueryRaw<int?>("select Value = [dbo].[fu_app_changelog_session_id]()").SingleAsync();

        [DbFunction("fu_app_userid", "dbo")]
        public static int? fu_app_userid()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        public async Task<int?> fu_app_useridAsync()
            => await Database.SqlQueryRaw<int?>("select Value = [dbo].[fu_app_userid]()").SingleAsync();

        [DbFunction("FUsedArticles", "dbo")]
        public IQueryable<FUsedArticlesResult> FUsedArticles(int? P_componentID)
        {
            return FromExpression(() => FUsedArticles(P_componentID));
        }

        [DbFunction("FUsedArticlesScheduledTasks", "dbo")]
        public IQueryable<FUsedArticlesScheduledTasksResult> FUsedArticlesScheduledTasks(int? P_componentID)
        {
            return FromExpression(() => FUsedArticlesScheduledTasks(P_componentID));
        }

        [DbFunction("FUsedArticlesUnscheduledTasks", "dbo")]
        public IQueryable<FUsedArticlesUnscheduledTasksResult> FUsedArticlesUnscheduledTasks(int? P_componentID)
        {
            return FromExpression(() => FUsedArticlesUnscheduledTasks(P_componentID));
        }

        [DbFunction("FUserRolesOnly", "dbo")]
        public IQueryable<FUserRolesOnlyResult> FUserRolesOnly(int? p_empID, int? p_roleID)
        {
            return FromExpression(() => FUserRolesOnly(p_empID, p_roleID));
        }

        [DbFunction("FWEBGetStock", "dbo")]
        public IQueryable<FWEBGetStockResult> FWEBGetStock(DateTime? p_date, int? p_groupID)
        {
            return FromExpression(() => FWEBGetStock(p_date, p_groupID));
        }

        [DbFunction("StringConcatenateAggregate", "dbo")]
        public static string StringConcatenateAggregate(string input, string separator)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("tvf_ComponentMoveCopyLogs_Debug", "dbo")]
        public IQueryable<tvf_ComponentMoveCopyLogs_DebugResult> tvf_ComponentMoveCopyLogs_Debug(long? ComponentID)
        {
            return FromExpression(() => tvf_ComponentMoveCopyLogs_Debug(ComponentID));
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<FAccessRightsResult>().HasNoKey();
            modelBuilder.Entity<FAliringarComponentsResult>().HasNoKey();
            modelBuilder.Entity<FArticlesResult>().HasNoKey();
            modelBuilder.Entity<FArticles_UnitsOfMeasure_ArticlesSuppliersResult>().HasNoKey();
            modelBuilder.Entity<FArticlesBelowMinimumStockResult>().HasNoKey();
            modelBuilder.Entity<FArticlesDefaultStocksResult>().HasNoKey();
            modelBuilder.Entity<FArticlesOpenedOrdersResult>().HasNoKey();
            modelBuilder.Entity<FComponentAllParentsResult>().HasNoKey();
            modelBuilder.Entity<FComponentClassesResult>().HasNoKey();
            modelBuilder.Entity<FComponentDataFieldsResult>().HasNoKey();
            modelBuilder.Entity<FComponentHoursResult>().HasNoKey();
            modelBuilder.Entity<FComponentHoursAllResult>().HasNoKey();
            modelBuilder.Entity<FComponentHoursAllV2Result>().HasNoKey();
            modelBuilder.Entity<FComponentListResult>().HasNoKey();
            modelBuilder.Entity<FComponentMoveCopyLogsResult>().HasNoKey();
            modelBuilder.Entity<FComponentsResult>().HasNoKey();
            modelBuilder.Entity<FComponentTreeResult>().HasNoKey();
            modelBuilder.Entity<FComponentTree_NEWResult>().HasNoKey();
            modelBuilder.Entity<FCountersResult>().HasNoKey();
            modelBuilder.Entity<FEmployeesResult>().HasNoKey();
            modelBuilder.Entity<FEmployeesByRoleIDResult>().HasNoKey();
            modelBuilder.Entity<FFilesArticlesResult>().HasNoKey();
            modelBuilder.Entity<FGetAllActiveTasksResult>().HasNoKey();
            modelBuilder.Entity<FGetAllRolesResult>().HasNoKey();
            modelBuilder.Entity<FGetArticleStockInformationResult>().HasNoKey();
            modelBuilder.Entity<FGetArticleTaskComponentIntervalResult>().HasNoKey();
            modelBuilder.Entity<FGetNAPRolesResult>().HasNoKey();
            modelBuilder.Entity<FGetOperationsResult>().HasNoKey();
            modelBuilder.Entity<FGetStockResult>().HasNoKey();
            modelBuilder.Entity<FGetStock_NEWResult>().HasNoKey();
            modelBuilder.Entity<FGetStockTotalResult>().HasNoKey();
            modelBuilder.Entity<FGetStockTotal_NEWResult>().HasNoKey();
            modelBuilder.Entity<FGetTaskLogsResult>().HasNoKey();
            modelBuilder.Entity<FGroupsOfArticlesResult>().HasNoKey();
            modelBuilder.Entity<FHDFBranchesResult>().HasNoKey();
            modelBuilder.Entity<FIntervalsResult>().HasNoKey();
            modelBuilder.Entity<FIntervalsDueDateResult>().HasNoKey();
            modelBuilder.Entity<FIntervalsLowerWeightResult>().HasNoKey();
            modelBuilder.Entity<FLastTaskLogRowResult>().HasNoKey();
            modelBuilder.Entity<FOneComponentTreeResult>().HasNoKey();
            modelBuilder.Entity<FOpenedOrdersQuantityResult>().HasNoKey();
            modelBuilder.Entity<FRacksResult>().HasNoKey();
            modelBuilder.Entity<FRptTaskSummary_AccomplishedTasksResult>().HasNoKey();
            modelBuilder.Entity<FRptTaskSummary_NextTasksResult>().HasNoKey();
            modelBuilder.Entity<FRptTaskSummary_NotificationsResult>().HasNoKey();
            modelBuilder.Entity<FRptTaskSummary_UnscheduledTasksResult>().HasNoKey();
            modelBuilder.Entity<FSelectScheduledUnscheduledTasksResult>().HasNoKey();
            modelBuilder.Entity<FShelvesResult>().HasNoKey();
            modelBuilder.Entity<FSplitStringToTableResult>().HasNoKey();
            modelBuilder.Entity<FStocksBelowMinimumResult>().HasNoKey();
            modelBuilder.Entity<FStocksListResult>().HasNoKey();
            modelBuilder.Entity<FSubComponentsResult>().HasNoKey();
            modelBuilder.Entity<FSubComponents1Result>().HasNoKey();
            modelBuilder.Entity<FSubComponentsAndParameterComponentResult>().HasNoKey();
            modelBuilder.Entity<FSuppliersResult>().HasNoKey();
            modelBuilder.Entity<FSuppliersInvoicesStatusResult>().HasNoKey();
            modelBuilder.Entity<FTableFieldComboBoxValuesResult>().HasNoKey();
            modelBuilder.Entity<FTaskClassesResult>().HasNoKey();
            modelBuilder.Entity<FTaskFieldDataResult>().HasNoKey();
            modelBuilder.Entity<FTasksResult>().HasNoKey();
            modelBuilder.Entity<FTasksStatusResult>().HasNoKey();
            modelBuilder.Entity<FTaskTypesResult>().HasNoKey();
            modelBuilder.Entity<FUsedArticlesResult>().HasNoKey();
            modelBuilder.Entity<FUsedArticlesScheduledTasksResult>().HasNoKey();
            modelBuilder.Entity<FUsedArticlesUnscheduledTasksResult>().HasNoKey();
            modelBuilder.Entity<FUserRolesOnlyResult>().HasNoKey();
            modelBuilder.Entity<FWEBGetStockResult>().HasNoKey();
            modelBuilder.Entity<tvf_ComponentMoveCopyLogs_DebugResult>().HasNoKey();
        }
    }
}
